// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	interview "github.com/sedorofeevd/project-druzya/services/recommendation/internal/adapter/interview"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// AckOutboxEvents provides a mock function with given fields: ctx, ids
func (_m *Client) AckOutboxEvents(ctx context.Context, ids []string) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for AckOutboxEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_AckOutboxEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AckOutboxEvents'
type Client_AckOutboxEvents_Call struct {
	*mock.Call
}

// AckOutboxEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *Client_Expecter) AckOutboxEvents(ctx interface{}, ids interface{}) *Client_AckOutboxEvents_Call {
	return &Client_AckOutboxEvents_Call{Call: _e.mock.On("AckOutboxEvents", ctx, ids)}
}

func (_c *Client_AckOutboxEvents_Call) Run(run func(ctx context.Context, ids []string)) *Client_AckOutboxEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *Client_AckOutboxEvents_Call) Return(_a0 error) *Client_AckOutboxEvents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_AckOutboxEvents_Call) RunAndReturn(run func(context.Context, []string) error) *Client_AckOutboxEvents_Call {
	_c.Call.Return(run)
	return _c
}

// ClaimOutboxEvents provides a mock function with given fields: ctx, eventName, limit
func (_m *Client) ClaimOutboxEvents(ctx context.Context, eventName string, limit int) ([]interview.OutboxEvent, error) {
	ret := _m.Called(ctx, eventName, limit)

	if len(ret) == 0 {
		panic("no return value specified for ClaimOutboxEvents")
	}

	var r0 []interview.OutboxEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]interview.OutboxEvent, error)); ok {
		return rf(ctx, eventName, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []interview.OutboxEvent); ok {
		r0 = rf(ctx, eventName, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interview.OutboxEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, eventName, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ClaimOutboxEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimOutboxEvents'
type Client_ClaimOutboxEvents_Call struct {
	*mock.Call
}

// ClaimOutboxEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - eventName string
//   - limit int
func (_e *Client_Expecter) ClaimOutboxEvents(ctx interface{}, eventName interface{}, limit interface{}) *Client_ClaimOutboxEvents_Call {
	return &Client_ClaimOutboxEvents_Call{Call: _e.mock.On("ClaimOutboxEvents", ctx, eventName, limit)}
}

func (_c *Client_ClaimOutboxEvents_Call) Run(run func(ctx context.Context, eventName string, limit int)) *Client_ClaimOutboxEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *Client_ClaimOutboxEvents_Call) Return(_a0 []interview.OutboxEvent, _a1 error) *Client_ClaimOutboxEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_ClaimOutboxEvents_Call) RunAndReturn(run func(context.Context, string, int) ([]interview.OutboxEvent, error)) *Client_ClaimOutboxEvents_Call {
	_c.Call.Return(run)
	return _c
}

// FailOutboxEvent provides a mock function with given fields: ctx, id, errMsg
func (_m *Client) FailOutboxEvent(ctx context.Context, id string, errMsg string) error {
	ret := _m.Called(ctx, id, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for FailOutboxEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, errMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_FailOutboxEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailOutboxEvent'
type Client_FailOutboxEvent_Call struct {
	*mock.Call
}

// FailOutboxEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - errMsg string
func (_e *Client_Expecter) FailOutboxEvent(ctx interface{}, id interface{}, errMsg interface{}) *Client_FailOutboxEvent_Call {
	return &Client_FailOutboxEvent_Call{Call: _e.mock.On("FailOutboxEvent", ctx, id, errMsg)}
}

func (_c *Client_FailOutboxEvent_Call) Run(run func(ctx context.Context, id string, errMsg string)) *Client_FailOutboxEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Client_FailOutboxEvent_Call) Return(_a0 error) *Client_FailOutboxEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_FailOutboxEvent_Call) RunAndReturn(run func(context.Context, string, string) error) *Client_FailOutboxEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvaluationSummary provides a mock function with given fields: ctx, attemptID
func (_m *Client) GetEvaluationSummary(ctx context.Context, attemptID string) (*interview.EvaluationSummary, error) {
	ret := _m.Called(ctx, attemptID)

	if len(ret) == 0 {
		panic("no return value specified for GetEvaluationSummary")
	}

	var r0 *interview.EvaluationSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*interview.EvaluationSummary, error)); ok {
		return rf(ctx, attemptID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *interview.EvaluationSummary); ok {
		r0 = rf(ctx, attemptID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interview.EvaluationSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, attemptID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetEvaluationSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvaluationSummary'
type Client_GetEvaluationSummary_Call struct {
	*mock.Call
}

// GetEvaluationSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - attemptID string
func (_e *Client_Expecter) GetEvaluationSummary(ctx interface{}, attemptID interface{}) *Client_GetEvaluationSummary_Call {
	return &Client_GetEvaluationSummary_Call{Call: _e.mock.On("GetEvaluationSummary", ctx, attemptID)}
}

func (_c *Client_GetEvaluationSummary_Call) Run(run func(ctx context.Context, attemptID string)) *Client_GetEvaluationSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_GetEvaluationSummary_Call) Return(_a0 *interview.EvaluationSummary, _a1 error) *Client_GetEvaluationSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetEvaluationSummary_Call) RunAndReturn(run func(context.Context, string) (*interview.EvaluationSummary, error)) *Client_GetEvaluationSummary_Call {
	_c.Call.Return(run)
	return _c
}

// ListPendingRetryItems provides a mock function with given fields: ctx, userID
func (_m *Client) ListPendingRetryItems(ctx context.Context, userID string) ([]interview.RetryItem, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingRetryItems")
	}

	var r0 []interview.RetryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]interview.RetryItem, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []interview.RetryItem); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interview.RetryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ListPendingRetryItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPendingRetryItems'
type Client_ListPendingRetryItems_Call struct {
	*mock.Call
}

// ListPendingRetryItems is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Client_Expecter) ListPendingRetryItems(ctx interface{}, userID interface{}) *Client_ListPendingRetryItems_Call {
	return &Client_ListPendingRetryItems_Call{Call: _e.mock.On("ListPendingRetryItems", ctx, userID)}
}

func (_c *Client_ListPendingRetryItems_Call) Run(run func(ctx context.Context, userID string)) *Client_ListPendingRetryItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_ListPendingRetryItems_Call) Return(_a0 []interview.RetryItem, _a1 error) *Client_ListPendingRetryItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_ListPendingRetryItems_Call) RunAndReturn(run func(context.Context, string) ([]interview.RetryItem, error)) *Client_ListPendingRetryItems_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
