// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/sedorofeevd/project-druzya/services/template/internal/example/model"
)

// ItemReader is an autogenerated mock type for the ItemReader type
type ItemReader struct {
	mock.Mock
}

type ItemReader_Expecter struct {
	mock *mock.Mock
}

func (_m *ItemReader) EXPECT() *ItemReader_Expecter {
	return &ItemReader_Expecter{mock: &_m.Mock}
}

// GetItemByID provides a mock function with given fields: ctx, id
func (_m *ItemReader) GetItemByID(ctx context.Context, id string) (*model.Item, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetItemByID")
	}

	var r0 *model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Item, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Item); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ItemReader_GetItemByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemByID'
type ItemReader_GetItemByID_Call struct {
	*mock.Call
}

// GetItemByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ItemReader_Expecter) GetItemByID(ctx interface{}, id interface{}) *ItemReader_GetItemByID_Call {
	return &ItemReader_GetItemByID_Call{Call: _e.mock.On("GetItemByID", ctx, id)}
}

func (_c *ItemReader_GetItemByID_Call) Run(run func(ctx context.Context, id string)) *ItemReader_GetItemByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ItemReader_GetItemByID_Call) Return(_a0 *model.Item, _a1 error) *ItemReader_GetItemByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ItemReader_GetItemByID_Call) RunAndReturn(run func(context.Context, string) (*model.Item, error)) *ItemReader_GetItemByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemBySlug provides a mock function with given fields: ctx, slug
func (_m *ItemReader) GetItemBySlug(ctx context.Context, slug string) (*model.Item, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetItemBySlug")
	}

	var r0 *model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Item, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Item); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ItemReader_GetItemBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemBySlug'
type ItemReader_GetItemBySlug_Call struct {
	*mock.Call
}

// GetItemBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *ItemReader_Expecter) GetItemBySlug(ctx interface{}, slug interface{}) *ItemReader_GetItemBySlug_Call {
	return &ItemReader_GetItemBySlug_Call{Call: _e.mock.On("GetItemBySlug", ctx, slug)}
}

func (_c *ItemReader_GetItemBySlug_Call) Run(run func(ctx context.Context, slug string)) *ItemReader_GetItemBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ItemReader_GetItemBySlug_Call) Return(_a0 *model.Item, _a1 error) *ItemReader_GetItemBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ItemReader_GetItemBySlug_Call) RunAndReturn(run func(context.Context, string) (*model.Item, error)) *ItemReader_GetItemBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// NewItemReader creates a new instance of ItemReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewItemReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *ItemReader {
	mock := &ItemReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
