// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	content "github.com/sedorofeevd/project-druzya/services/interview/internal/adapter/content"

	mock "github.com/stretchr/testify/mock"
)

// ContentClient is an autogenerated mock type for the ContentClient type
type ContentClient struct {
	mock.Mock
}

type ContentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ContentClient) EXPECT() *ContentClient_Expecter {
	return &ContentClient_Expecter{mock: &_m.Mock}
}

// GetTask provides a mock function with given fields: ctx, taskID
func (_m *ContentClient) GetTask(ctx context.Context, taskID string) (*content.Task, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 *content.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*content.Task, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *content.Task); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContentClient_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type ContentClient_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *ContentClient_Expecter) GetTask(ctx interface{}, taskID interface{}) *ContentClient_GetTask_Call {
	return &ContentClient_GetTask_Call{Call: _e.mock.On("GetTask", ctx, taskID)}
}

func (_c *ContentClient_GetTask_Call) Run(run func(ctx context.Context, taskID string)) *ContentClient_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ContentClient_GetTask_Call) Return(_a0 *content.Task, _a1 error) *ContentClient_GetTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContentClient_GetTask_Call) RunAndReturn(run func(context.Context, string) (*content.Task, error)) *ContentClient_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewContentClient creates a new instance of ContentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContentClient {
	mock := &ContentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
