// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/sedorofeevd/project-druzya/services/interview/internal/interview/model"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CreateAttempt provides a mock function with given fields: ctx, attempt
func (_m *Repository) CreateAttempt(ctx context.Context, attempt *model.Attempt) error {
	ret := _m.Called(ctx, attempt)

	if len(ret) == 0 {
		panic("no return value specified for CreateAttempt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Attempt) error); ok {
		r0 = rf(ctx, attempt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_CreateAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAttempt'
type Repository_CreateAttempt_Call struct {
	*mock.Call
}

// CreateAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - attempt *model.Attempt
func (_e *Repository_Expecter) CreateAttempt(ctx interface{}, attempt interface{}) *Repository_CreateAttempt_Call {
	return &Repository_CreateAttempt_Call{Call: _e.mock.On("CreateAttempt", ctx, attempt)}
}

func (_c *Repository_CreateAttempt_Call) Run(run func(ctx context.Context, attempt *model.Attempt)) *Repository_CreateAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Attempt))
	})
	return _c
}

func (_c *Repository_CreateAttempt_Call) Return(_a0 error) *Repository_CreateAttempt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_CreateAttempt_Call) RunAndReturn(run func(context.Context, *model.Attempt) error) *Repository_CreateAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionForUser provides a mock function with given fields: ctx, userID, sessionID
func (_m *Repository) GetSessionForUser(ctx context.Context, userID string, sessionID string) (*model.Session, error) {
	ret := _m.Called(ctx, userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionForUser")
	}

	var r0 *model.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Session, error)); ok {
		return rf(ctx, userID, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Session); ok {
		r0 = rf(ctx, userID, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetSessionForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionForUser'
type Repository_GetSessionForUser_Call struct {
	*mock.Call
}

// GetSessionForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - sessionID string
func (_e *Repository_Expecter) GetSessionForUser(ctx interface{}, userID interface{}, sessionID interface{}) *Repository_GetSessionForUser_Call {
	return &Repository_GetSessionForUser_Call{Call: _e.mock.On("GetSessionForUser", ctx, userID, sessionID)}
}

func (_c *Repository_GetSessionForUser_Call) Run(run func(ctx context.Context, userID string, sessionID string)) *Repository_GetSessionForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_GetSessionForUser_Call) Return(_a0 *model.Session, _a1 error) *Repository_GetSessionForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetSessionForUser_Call) RunAndReturn(run func(context.Context, string, string) (*model.Session, error)) *Repository_GetSessionForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionTaskForUser provides a mock function with given fields: ctx, userID, sessionTaskID
func (_m *Repository) GetSessionTaskForUser(ctx context.Context, userID string, sessionTaskID string) (*model.SessionTask, error) {
	ret := _m.Called(ctx, userID, sessionTaskID)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionTaskForUser")
	}

	var r0 *model.SessionTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.SessionTask, error)); ok {
		return rf(ctx, userID, sessionTaskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.SessionTask); ok {
		r0 = rf(ctx, userID, sessionTaskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SessionTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, sessionTaskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetSessionTaskForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionTaskForUser'
type Repository_GetSessionTaskForUser_Call struct {
	*mock.Call
}

// GetSessionTaskForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - sessionTaskID string
func (_e *Repository_Expecter) GetSessionTaskForUser(ctx interface{}, userID interface{}, sessionTaskID interface{}) *Repository_GetSessionTaskForUser_Call {
	return &Repository_GetSessionTaskForUser_Call{Call: _e.mock.On("GetSessionTaskForUser", ctx, userID, sessionTaskID)}
}

func (_c *Repository_GetSessionTaskForUser_Call) Run(run func(ctx context.Context, userID string, sessionTaskID string)) *Repository_GetSessionTaskForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_GetSessionTaskForUser_Call) Return(_a0 *model.SessionTask, _a1 error) *Repository_GetSessionTaskForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetSessionTaskForUser_Call) RunAndReturn(run func(context.Context, string, string) (*model.SessionTask, error)) *Repository_GetSessionTaskForUser_Call {
	_c.Call.Return(run)
	return _c
}

// InsertOutbox provides a mock function with given fields: ctx, eventName, payload
func (_m *Repository) InsertOutbox(ctx context.Context, eventName string, payload map[string]interface{}) error {
	ret := _m.Called(ctx, eventName, payload)

	if len(ret) == 0 {
		panic("no return value specified for InsertOutbox")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, eventName, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_InsertOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertOutbox'
type Repository_InsertOutbox_Call struct {
	*mock.Call
}

// InsertOutbox is a helper method to define mock.On call
//   - ctx context.Context
//   - eventName string
//   - payload map[string]interface{}
func (_e *Repository_Expecter) InsertOutbox(ctx interface{}, eventName interface{}, payload interface{}) *Repository_InsertOutbox_Call {
	return &Repository_InsertOutbox_Call{Call: _e.mock.On("InsertOutbox", ctx, eventName, payload)}
}

func (_c *Repository_InsertOutbox_Call) Run(run func(ctx context.Context, eventName string, payload map[string]interface{})) *Repository_InsertOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *Repository_InsertOutbox_Call) Return(_a0 error) *Repository_InsertOutbox_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_InsertOutbox_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}) error) *Repository_InsertOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSession provides a mock function with given fields: ctx, session
func (_m *Repository) UpdateSession(ctx context.Context, session *model.Session) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSession'
type Repository_UpdateSession_Call struct {
	*mock.Call
}

// UpdateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session *model.Session
func (_e *Repository_Expecter) UpdateSession(ctx interface{}, session interface{}) *Repository_UpdateSession_Call {
	return &Repository_UpdateSession_Call{Call: _e.mock.On("UpdateSession", ctx, session)}
}

func (_c *Repository_UpdateSession_Call) Run(run func(ctx context.Context, session *model.Session)) *Repository_UpdateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Session))
	})
	return _c
}

func (_c *Repository_UpdateSession_Call) Return(_a0 error) *Repository_UpdateSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateSession_Call) RunAndReturn(run func(context.Context, *model.Session) error) *Repository_UpdateSession_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSessionTask provides a mock function with given fields: ctx, task
func (_m *Repository) UpdateSessionTask(ctx context.Context, task *model.SessionTask) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSessionTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SessionTask) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateSessionTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSessionTask'
type Repository_UpdateSessionTask_Call struct {
	*mock.Call
}

// UpdateSessionTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task *model.SessionTask
func (_e *Repository_Expecter) UpdateSessionTask(ctx interface{}, task interface{}) *Repository_UpdateSessionTask_Call {
	return &Repository_UpdateSessionTask_Call{Call: _e.mock.On("UpdateSessionTask", ctx, task)}
}

func (_c *Repository_UpdateSessionTask_Call) Run(run func(ctx context.Context, task *model.SessionTask)) *Repository_UpdateSessionTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SessionTask))
	})
	return _c
}

func (_c *Repository_UpdateSessionTask_Call) Return(_a0 error) *Repository_UpdateSessionTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateSessionTask_Call) RunAndReturn(run func(context.Context, *model.SessionTask) error) *Repository_UpdateSessionTask_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function with given fields: ctx, fn
func (_m *Repository) WithTx(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type Repository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *Repository_Expecter) WithTx(ctx interface{}, fn interface{}) *Repository_WithTx_Call {
	return &Repository_WithTx_Call{Call: _e.mock.On("WithTx", ctx, fn)}
}

func (_c *Repository_WithTx_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *Repository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *Repository_WithTx_Call) Return(_a0 error) *Repository_WithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_WithTx_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *Repository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
