// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/sedorofeevd/project-druzya/services/recommendation/internal/recommendation/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CreateRetryTaskPlanItem provides a mock function with given fields: ctx, item
func (_m *Repository) CreateRetryTaskPlanItem(ctx context.Context, item model.LearningPlanItem) (*model.LearningPlanItem, error) {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for CreateRetryTaskPlanItem")
	}

	var r0 *model.LearningPlanItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.LearningPlanItem) (*model.LearningPlanItem, error)); ok {
		return rf(ctx, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.LearningPlanItem) *model.LearningPlanItem); ok {
		r0 = rf(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.LearningPlanItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.LearningPlanItem) error); ok {
		r1 = rf(ctx, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CreateRetryTaskPlanItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRetryTaskPlanItem'
type Repository_CreateRetryTaskPlanItem_Call struct {
	*mock.Call
}

// CreateRetryTaskPlanItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item model.LearningPlanItem
func (_e *Repository_Expecter) CreateRetryTaskPlanItem(ctx interface{}, item interface{}) *Repository_CreateRetryTaskPlanItem_Call {
	return &Repository_CreateRetryTaskPlanItem_Call{Call: _e.mock.On("CreateRetryTaskPlanItem", ctx, item)}
}

func (_c *Repository_CreateRetryTaskPlanItem_Call) Run(run func(ctx context.Context, item model.LearningPlanItem)) *Repository_CreateRetryTaskPlanItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.LearningPlanItem))
	})
	return _c
}

func (_c *Repository_CreateRetryTaskPlanItem_Call) Return(_a0 *model.LearningPlanItem, _a1 error) *Repository_CreateRetryTaskPlanItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CreateRetryTaskPlanItem_Call) RunAndReturn(run func(context.Context, model.LearningPlanItem) (*model.LearningPlanItem, error)) *Repository_CreateRetryTaskPlanItem_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureUserProfile provides a mock function with given fields: ctx, userID
func (_m *Repository) EnsureUserProfile(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for EnsureUserProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_EnsureUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureUserProfile'
type Repository_EnsureUserProfile_Call struct {
	*mock.Call
}

// EnsureUserProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Repository_Expecter) EnsureUserProfile(ctx interface{}, userID interface{}) *Repository_EnsureUserProfile_Call {
	return &Repository_EnsureUserProfile_Call{Call: _e.mock.On("EnsureUserProfile", ctx, userID)}
}

func (_c *Repository_EnsureUserProfile_Call) Run(run func(ctx context.Context, userID string)) *Repository_EnsureUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_EnsureUserProfile_Call) Return(_a0 error) *Repository_EnsureUserProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_EnsureUserProfile_Call) RunAndReturn(run func(context.Context, string) error) *Repository_EnsureUserProfile_Call {
	_c.Call.Return(run)
	return _c
}

// FetchDashboardSnapshot provides a mock function with given fields: ctx, userID
func (_m *Repository) FetchDashboardSnapshot(ctx context.Context, userID string) (*model.DashboardSnapshot, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FetchDashboardSnapshot")
	}

	var r0 *model.DashboardSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.DashboardSnapshot, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.DashboardSnapshot); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DashboardSnapshot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FetchDashboardSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchDashboardSnapshot'
type Repository_FetchDashboardSnapshot_Call struct {
	*mock.Call
}

// FetchDashboardSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Repository_Expecter) FetchDashboardSnapshot(ctx interface{}, userID interface{}) *Repository_FetchDashboardSnapshot_Call {
	return &Repository_FetchDashboardSnapshot_Call{Call: _e.mock.On("FetchDashboardSnapshot", ctx, userID)}
}

func (_c *Repository_FetchDashboardSnapshot_Call) Run(run func(ctx context.Context, userID string)) *Repository_FetchDashboardSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_FetchDashboardSnapshot_Call) Return(_a0 *model.DashboardSnapshot, _a1 error) *Repository_FetchDashboardSnapshot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FetchDashboardSnapshot_Call) RunAndReturn(run func(context.Context, string) (*model.DashboardSnapshot, error)) *Repository_FetchDashboardSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// GetLearningPlanItem provides a mock function with given fields: ctx, userID, id
func (_m *Repository) GetLearningPlanItem(ctx context.Context, userID string, id string) (*model.LearningPlanItem, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLearningPlanItem")
	}

	var r0 *model.LearningPlanItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.LearningPlanItem, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.LearningPlanItem); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.LearningPlanItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetLearningPlanItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLearningPlanItem'
type Repository_GetLearningPlanItem_Call struct {
	*mock.Call
}

// GetLearningPlanItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *Repository_Expecter) GetLearningPlanItem(ctx interface{}, userID interface{}, id interface{}) *Repository_GetLearningPlanItem_Call {
	return &Repository_GetLearningPlanItem_Call{Call: _e.mock.On("GetLearningPlanItem", ctx, userID, id)}
}

func (_c *Repository_GetLearningPlanItem_Call) Run(run func(ctx context.Context, userID string, id string)) *Repository_GetLearningPlanItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_GetLearningPlanItem_Call) Return(_a0 *model.LearningPlanItem, _a1 error) *Repository_GetLearningPlanItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetLearningPlanItem_Call) RunAndReturn(run func(context.Context, string, string) (*model.LearningPlanItem, error)) *Repository_GetLearningPlanItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecommendation provides a mock function with given fields: ctx, userID, id
func (_m *Repository) GetRecommendation(ctx context.Context, userID string, id string) (*model.Recommendation, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRecommendation")
	}

	var r0 *model.Recommendation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Recommendation, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Recommendation); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Recommendation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetRecommendation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecommendation'
type Repository_GetRecommendation_Call struct {
	*mock.Call
}

// GetRecommendation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *Repository_Expecter) GetRecommendation(ctx interface{}, userID interface{}, id interface{}) *Repository_GetRecommendation_Call {
	return &Repository_GetRecommendation_Call{Call: _e.mock.On("GetRecommendation", ctx, userID, id)}
}

func (_c *Repository_GetRecommendation_Call) Run(run func(ctx context.Context, userID string, id string)) *Repository_GetRecommendation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_GetRecommendation_Call) Return(_a0 *model.Recommendation, _a1 error) *Repository_GetRecommendation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetRecommendation_Call) RunAndReturn(run func(context.Context, string, string) (*model.Recommendation, error)) *Repository_GetRecommendation_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserProfile provides a mock function with given fields: ctx, userID
func (_m *Repository) GetUserProfile(ctx context.Context, userID string) (*model.UserSkillProfile, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserProfile")
	}

	var r0 *model.UserSkillProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserSkillProfile, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserSkillProfile); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserSkillProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserProfile'
type Repository_GetUserProfile_Call struct {
	*mock.Call
}

// GetUserProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Repository_Expecter) GetUserProfile(ctx interface{}, userID interface{}) *Repository_GetUserProfile_Call {
	return &Repository_GetUserProfile_Call{Call: _e.mock.On("GetUserProfile", ctx, userID)}
}

func (_c *Repository_GetUserProfile_Call) Run(run func(ctx context.Context, userID string)) *Repository_GetUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_GetUserProfile_Call) Return(_a0 *model.UserSkillProfile, _a1 error) *Repository_GetUserProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetUserProfile_Call) RunAndReturn(run func(context.Context, string) (*model.UserSkillProfile, error)) *Repository_GetUserProfile_Call {
	_c.Call.Return(run)
	return _c
}

// InsertSpecialRecommendation provides a mock function with given fields: ctx, rec
func (_m *Repository) InsertSpecialRecommendation(ctx context.Context, rec model.Recommendation) (*model.Recommendation, error) {
	ret := _m.Called(ctx, rec)

	if len(ret) == 0 {
		panic("no return value specified for InsertSpecialRecommendation")
	}

	var r0 *model.Recommendation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Recommendation) (*model.Recommendation, error)); ok {
		return rf(ctx, rec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Recommendation) *model.Recommendation); ok {
		r0 = rf(ctx, rec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Recommendation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Recommendation) error); ok {
		r1 = rf(ctx, rec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_InsertSpecialRecommendation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertSpecialRecommendation'
type Repository_InsertSpecialRecommendation_Call struct {
	*mock.Call
}

// InsertSpecialRecommendation is a helper method to define mock.On call
//   - ctx context.Context
//   - rec model.Recommendation
func (_e *Repository_Expecter) InsertSpecialRecommendation(ctx interface{}, rec interface{}) *Repository_InsertSpecialRecommendation_Call {
	return &Repository_InsertSpecialRecommendation_Call{Call: _e.mock.On("InsertSpecialRecommendation", ctx, rec)}
}

func (_c *Repository_InsertSpecialRecommendation_Call) Run(run func(ctx context.Context, rec model.Recommendation)) *Repository_InsertSpecialRecommendation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Recommendation))
	})
	return _c
}

func (_c *Repository_InsertSpecialRecommendation_Call) Return(_a0 *model.Recommendation, _a1 error) *Repository_InsertSpecialRecommendation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_InsertSpecialRecommendation_Call) RunAndReturn(run func(context.Context, model.Recommendation) (*model.Recommendation, error)) *Repository_InsertSpecialRecommendation_Call {
	_c.Call.Return(run)
	return _c
}

// InsertTakeMockRecommendation provides a mock function with given fields: ctx, rec
func (_m *Repository) InsertTakeMockRecommendation(ctx context.Context, rec model.Recommendation) (*model.Recommendation, error) {
	ret := _m.Called(ctx, rec)

	if len(ret) == 0 {
		panic("no return value specified for InsertTakeMockRecommendation")
	}

	var r0 *model.Recommendation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Recommendation) (*model.Recommendation, error)); ok {
		return rf(ctx, rec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Recommendation) *model.Recommendation); ok {
		r0 = rf(ctx, rec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Recommendation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Recommendation) error); ok {
		r1 = rf(ctx, rec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_InsertTakeMockRecommendation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertTakeMockRecommendation'
type Repository_InsertTakeMockRecommendation_Call struct {
	*mock.Call
}

// InsertTakeMockRecommendation is a helper method to define mock.On call
//   - ctx context.Context
//   - rec model.Recommendation
func (_e *Repository_Expecter) InsertTakeMockRecommendation(ctx interface{}, rec interface{}) *Repository_InsertTakeMockRecommendation_Call {
	return &Repository_InsertTakeMockRecommendation_Call{Call: _e.mock.On("InsertTakeMockRecommendation", ctx, rec)}
}

func (_c *Repository_InsertTakeMockRecommendation_Call) Run(run func(ctx context.Context, rec model.Recommendation)) *Repository_InsertTakeMockRecommendation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Recommendation))
	})
	return _c
}

func (_c *Repository_InsertTakeMockRecommendation_Call) Return(_a0 *model.Recommendation, _a1 error) *Repository_InsertTakeMockRecommendation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_InsertTakeMockRecommendation_Call) RunAndReturn(run func(context.Context, model.Recommendation) (*model.Recommendation, error)) *Repository_InsertTakeMockRecommendation_Call {
	_c.Call.Return(run)
	return _c
}

// IsEventProcessed provides a mock function with given fields: ctx, consumer, eventID
func (_m *Repository) IsEventProcessed(ctx context.Context, consumer string, eventID string) (bool, error) {
	ret := _m.Called(ctx, consumer, eventID)

	if len(ret) == 0 {
		panic("no return value specified for IsEventProcessed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, consumer, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, consumer, eventID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, consumer, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_IsEventProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEventProcessed'
type Repository_IsEventProcessed_Call struct {
	*mock.Call
}

// IsEventProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - consumer string
//   - eventID string
func (_e *Repository_Expecter) IsEventProcessed(ctx interface{}, consumer interface{}, eventID interface{}) *Repository_IsEventProcessed_Call {
	return &Repository_IsEventProcessed_Call{Call: _e.mock.On("IsEventProcessed", ctx, consumer, eventID)}
}

func (_c *Repository_IsEventProcessed_Call) Run(run func(ctx context.Context, consumer string, eventID string)) *Repository_IsEventProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_IsEventProcessed_Call) Return(_a0 bool, _a1 error) *Repository_IsEventProcessed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_IsEventProcessed_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *Repository_IsEventProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveLearningPlanItems provides a mock function with given fields: ctx, userID
func (_m *Repository) ListActiveLearningPlanItems(ctx context.Context, userID string) ([]model.LearningPlanItem, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveLearningPlanItems")
	}

	var r0 []model.LearningPlanItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.LearningPlanItem, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.LearningPlanItem); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.LearningPlanItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListActiveLearningPlanItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveLearningPlanItems'
type Repository_ListActiveLearningPlanItems_Call struct {
	*mock.Call
}

// ListActiveLearningPlanItems is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Repository_Expecter) ListActiveLearningPlanItems(ctx interface{}, userID interface{}) *Repository_ListActiveLearningPlanItems_Call {
	return &Repository_ListActiveLearningPlanItems_Call{Call: _e.mock.On("ListActiveLearningPlanItems", ctx, userID)}
}

func (_c *Repository_ListActiveLearningPlanItems_Call) Run(run func(ctx context.Context, userID string)) *Repository_ListActiveLearningPlanItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_ListActiveLearningPlanItems_Call) Return(_a0 []model.LearningPlanItem, _a1 error) *Repository_ListActiveLearningPlanItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListActiveLearningPlanItems_Call) RunAndReturn(run func(context.Context, string) ([]model.LearningPlanItem, error)) *Repository_ListActiveLearningPlanItems_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveRecommendations provides a mock function with given fields: ctx, userID
func (_m *Repository) ListActiveRecommendations(ctx context.Context, userID string) ([]model.Recommendation, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveRecommendations")
	}

	var r0 []model.Recommendation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Recommendation, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Recommendation); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Recommendation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListActiveRecommendations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveRecommendations'
type Repository_ListActiveRecommendations_Call struct {
	*mock.Call
}

// ListActiveRecommendations is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Repository_Expecter) ListActiveRecommendations(ctx interface{}, userID interface{}) *Repository_ListActiveRecommendations_Call {
	return &Repository_ListActiveRecommendations_Call{Call: _e.mock.On("ListActiveRecommendations", ctx, userID)}
}

func (_c *Repository_ListActiveRecommendations_Call) Run(run func(ctx context.Context, userID string)) *Repository_ListActiveRecommendations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_ListActiveRecommendations_Call) Return(_a0 []model.Recommendation, _a1 error) *Repository_ListActiveRecommendations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListActiveRecommendations_Call) RunAndReturn(run func(context.Context, string) ([]model.Recommendation, error)) *Repository_ListActiveRecommendations_Call {
	_c.Call.Return(run)
	return _c
}

// ListSkillScoresByUser provides a mock function with given fields: ctx, userID
func (_m *Repository) ListSkillScoresByUser(ctx context.Context, userID string) ([]model.SkillScore, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListSkillScoresByUser")
	}

	var r0 []model.SkillScore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.SkillScore, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.SkillScore); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SkillScore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListSkillScoresByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSkillScoresByUser'
type Repository_ListSkillScoresByUser_Call struct {
	*mock.Call
}

// ListSkillScoresByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Repository_Expecter) ListSkillScoresByUser(ctx interface{}, userID interface{}) *Repository_ListSkillScoresByUser_Call {
	return &Repository_ListSkillScoresByUser_Call{Call: _e.mock.On("ListSkillScoresByUser", ctx, userID)}
}

func (_c *Repository_ListSkillScoresByUser_Call) Run(run func(ctx context.Context, userID string)) *Repository_ListSkillScoresByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_ListSkillScoresByUser_Call) Return(_a0 []model.SkillScore, _a1 error) *Repository_ListSkillScoresByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListSkillScoresByUser_Call) RunAndReturn(run func(context.Context, string) ([]model.SkillScore, error)) *Repository_ListSkillScoresByUser_Call {
	_c.Call.Return(run)
	return _c
}

// MarkEventProcessed provides a mock function with given fields: ctx, consumer, eventID
func (_m *Repository) MarkEventProcessed(ctx context.Context, consumer string, eventID string) error {
	ret := _m.Called(ctx, consumer, eventID)

	if len(ret) == 0 {
		panic("no return value specified for MarkEventProcessed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, consumer, eventID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_MarkEventProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkEventProcessed'
type Repository_MarkEventProcessed_Call struct {
	*mock.Call
}

// MarkEventProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - consumer string
//   - eventID string
func (_e *Repository_Expecter) MarkEventProcessed(ctx interface{}, consumer interface{}, eventID interface{}) *Repository_MarkEventProcessed_Call {
	return &Repository_MarkEventProcessed_Call{Call: _e.mock.On("MarkEventProcessed", ctx, consumer, eventID)}
}

func (_c *Repository_MarkEventProcessed_Call) Run(run func(ctx context.Context, consumer string, eventID string)) *Repository_MarkEventProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_MarkEventProcessed_Call) Return(_a0 error) *Repository_MarkEventProcessed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_MarkEventProcessed_Call) RunAndReturn(run func(context.Context, string, string) error) *Repository_MarkEventProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// NextLearningPlanPosition provides a mock function with given fields: ctx, userID
func (_m *Repository) NextLearningPlanPosition(ctx context.Context, userID string) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for NextLearningPlanPosition")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_NextLearningPlanPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextLearningPlanPosition'
type Repository_NextLearningPlanPosition_Call struct {
	*mock.Call
}

// NextLearningPlanPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Repository_Expecter) NextLearningPlanPosition(ctx interface{}, userID interface{}) *Repository_NextLearningPlanPosition_Call {
	return &Repository_NextLearningPlanPosition_Call{Call: _e.mock.On("NextLearningPlanPosition", ctx, userID)}
}

func (_c *Repository_NextLearningPlanPosition_Call) Run(run func(ctx context.Context, userID string)) *Repository_NextLearningPlanPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_NextLearningPlanPosition_Call) Return(_a0 int, _a1 error) *Repository_NextLearningPlanPosition_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_NextLearningPlanPosition_Call) RunAndReturn(run func(context.Context, string) (int, error)) *Repository_NextLearningPlanPosition_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLearningPlanItemStatus provides a mock function with given fields: ctx, userID, id, status
func (_m *Repository) UpdateLearningPlanItemStatus(ctx context.Context, userID string, id string, status string) error {
	ret := _m.Called(ctx, userID, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLearningPlanItemStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, userID, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateLearningPlanItemStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLearningPlanItemStatus'
type Repository_UpdateLearningPlanItemStatus_Call struct {
	*mock.Call
}

// UpdateLearningPlanItemStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
//   - status string
func (_e *Repository_Expecter) UpdateLearningPlanItemStatus(ctx interface{}, userID interface{}, id interface{}, status interface{}) *Repository_UpdateLearningPlanItemStatus_Call {
	return &Repository_UpdateLearningPlanItemStatus_Call{Call: _e.mock.On("UpdateLearningPlanItemStatus", ctx, userID, id, status)}
}

func (_c *Repository_UpdateLearningPlanItemStatus_Call) Run(run func(ctx context.Context, userID string, id string, status string)) *Repository_UpdateLearningPlanItemStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Repository_UpdateLearningPlanItemStatus_Call) Return(_a0 error) *Repository_UpdateLearningPlanItemStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateLearningPlanItemStatus_Call) RunAndReturn(run func(context.Context, string, string, string) error) *Repository_UpdateLearningPlanItemStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfileSummary provides a mock function with given fields: ctx, userID, summary
func (_m *Repository) UpdateProfileSummary(ctx context.Context, userID string, summary string) error {
	ret := _m.Called(ctx, userID, summary)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfileSummary")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, summary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateProfileSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfileSummary'
type Repository_UpdateProfileSummary_Call struct {
	*mock.Call
}

// UpdateProfileSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - summary string
func (_e *Repository_Expecter) UpdateProfileSummary(ctx interface{}, userID interface{}, summary interface{}) *Repository_UpdateProfileSummary_Call {
	return &Repository_UpdateProfileSummary_Call{Call: _e.mock.On("UpdateProfileSummary", ctx, userID, summary)}
}

func (_c *Repository_UpdateProfileSummary_Call) Run(run func(ctx context.Context, userID string, summary string)) *Repository_UpdateProfileSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_UpdateProfileSummary_Call) Return(_a0 error) *Repository_UpdateProfileSummary_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateProfileSummary_Call) RunAndReturn(run func(context.Context, string, string) error) *Repository_UpdateProfileSummary_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateReadinessScore provides a mock function with given fields: ctx, userID, readiness
func (_m *Repository) UpdateReadinessScore(ctx context.Context, userID string, readiness int) error {
	ret := _m.Called(ctx, userID, readiness)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReadinessScore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, userID, readiness)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateReadinessScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReadinessScore'
type Repository_UpdateReadinessScore_Call struct {
	*mock.Call
}

// UpdateReadinessScore is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - readiness int
func (_e *Repository_Expecter) UpdateReadinessScore(ctx interface{}, userID interface{}, readiness interface{}) *Repository_UpdateReadinessScore_Call {
	return &Repository_UpdateReadinessScore_Call{Call: _e.mock.On("UpdateReadinessScore", ctx, userID, readiness)}
}

func (_c *Repository_UpdateReadinessScore_Call) Run(run func(ctx context.Context, userID string, readiness int)) *Repository_UpdateReadinessScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *Repository_UpdateReadinessScore_Call) Return(_a0 error) *Repository_UpdateReadinessScore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateReadinessScore_Call) RunAndReturn(run func(context.Context, string, int) error) *Repository_UpdateReadinessScore_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRecommendationStatus provides a mock function with given fields: ctx, userID, id, status
func (_m *Repository) UpdateRecommendationStatus(ctx context.Context, userID string, id string, status string) error {
	ret := _m.Called(ctx, userID, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRecommendationStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, userID, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateRecommendationStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRecommendationStatus'
type Repository_UpdateRecommendationStatus_Call struct {
	*mock.Call
}

// UpdateRecommendationStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
//   - status string
func (_e *Repository_Expecter) UpdateRecommendationStatus(ctx interface{}, userID interface{}, id interface{}, status interface{}) *Repository_UpdateRecommendationStatus_Call {
	return &Repository_UpdateRecommendationStatus_Call{Call: _e.mock.On("UpdateRecommendationStatus", ctx, userID, id, status)}
}

func (_c *Repository_UpdateRecommendationStatus_Call) Run(run func(ctx context.Context, userID string, id string, status string)) *Repository_UpdateRecommendationStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Repository_UpdateRecommendationStatus_Call) Return(_a0 error) *Repository_UpdateRecommendationStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateRecommendationStatus_Call) RunAndReturn(run func(context.Context, string, string, string) error) *Repository_UpdateRecommendationStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertImproveSkillRecommendation provides a mock function with given fields: ctx, rec
func (_m *Repository) UpsertImproveSkillRecommendation(ctx context.Context, rec model.Recommendation) (*model.Recommendation, error) {
	ret := _m.Called(ctx, rec)

	if len(ret) == 0 {
		panic("no return value specified for UpsertImproveSkillRecommendation")
	}

	var r0 *model.Recommendation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Recommendation) (*model.Recommendation, error)); ok {
		return rf(ctx, rec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Recommendation) *model.Recommendation); ok {
		r0 = rf(ctx, rec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Recommendation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Recommendation) error); ok {
		r1 = rf(ctx, rec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_UpsertImproveSkillRecommendation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertImproveSkillRecommendation'
type Repository_UpsertImproveSkillRecommendation_Call struct {
	*mock.Call
}

// UpsertImproveSkillRecommendation is a helper method to define mock.On call
//   - ctx context.Context
//   - rec model.Recommendation
func (_e *Repository_Expecter) UpsertImproveSkillRecommendation(ctx interface{}, rec interface{}) *Repository_UpsertImproveSkillRecommendation_Call {
	return &Repository_UpsertImproveSkillRecommendation_Call{Call: _e.mock.On("UpsertImproveSkillRecommendation", ctx, rec)}
}

func (_c *Repository_UpsertImproveSkillRecommendation_Call) Run(run func(ctx context.Context, rec model.Recommendation)) *Repository_UpsertImproveSkillRecommendation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Recommendation))
	})
	return _c
}

func (_c *Repository_UpsertImproveSkillRecommendation_Call) Return(_a0 *model.Recommendation, _a1 error) *Repository_UpsertImproveSkillRecommendation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_UpsertImproveSkillRecommendation_Call) RunAndReturn(run func(context.Context, model.Recommendation) (*model.Recommendation, error)) *Repository_UpsertImproveSkillRecommendation_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertSkillScore provides a mock function with given fields: ctx, userID, skillKey, normalized, seenAt
func (_m *Repository) UpsertSkillScore(ctx context.Context, userID string, skillKey string, normalized int, seenAt time.Time) (*model.SkillScore, error) {
	ret := _m.Called(ctx, userID, skillKey, normalized, seenAt)

	if len(ret) == 0 {
		panic("no return value specified for UpsertSkillScore")
	}

	var r0 *model.SkillScore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, time.Time) (*model.SkillScore, error)); ok {
		return rf(ctx, userID, skillKey, normalized, seenAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, time.Time) *model.SkillScore); ok {
		r0 = rf(ctx, userID, skillKey, normalized, seenAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SkillScore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, time.Time) error); ok {
		r1 = rf(ctx, userID, skillKey, normalized, seenAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_UpsertSkillScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertSkillScore'
type Repository_UpsertSkillScore_Call struct {
	*mock.Call
}

// UpsertSkillScore is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - skillKey string
//   - normalized int
//   - seenAt time.Time
func (_e *Repository_Expecter) UpsertSkillScore(ctx interface{}, userID interface{}, skillKey interface{}, normalized interface{}, seenAt interface{}) *Repository_UpsertSkillScore_Call {
	return &Repository_UpsertSkillScore_Call{Call: _e.mock.On("UpsertSkillScore", ctx, userID, skillKey, normalized, seenAt)}
}

func (_c *Repository_UpsertSkillScore_Call) Run(run func(ctx context.Context, userID string, skillKey string, normalized int, seenAt time.Time)) *Repository_UpsertSkillScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(time.Time))
	})
	return _c
}

func (_c *Repository_UpsertSkillScore_Call) Return(_a0 *model.SkillScore, _a1 error) *Repository_UpsertSkillScore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_UpsertSkillScore_Call) RunAndReturn(run func(context.Context, string, string, int, time.Time) (*model.SkillScore, error)) *Repository_UpsertSkillScore_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function with given fields: ctx, fn
func (_m *Repository) WithTx(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type Repository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *Repository_Expecter) WithTx(ctx interface{}, fn interface{}) *Repository_WithTx_Call {
	return &Repository_WithTx_Call{Call: _e.mock.On("WithTx", ctx, fn)}
}

func (_c *Repository_WithTx_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *Repository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *Repository_WithTx_Call) Return(_a0 error) *Repository_WithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_WithTx_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *Repository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
