// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/sedorofeevd/project-druzya/services/recommendation/internal/recommendation/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// ClaimEvent provides a mock function with given fields: ctx, consumer, eventID
func (_m *Repository) ClaimEvent(ctx context.Context, consumer string, eventID string) (bool, error) {
	ret := _m.Called(ctx, consumer, eventID)

	if len(ret) == 0 {
		panic("no return value specified for ClaimEvent")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, consumer, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, consumer, eventID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, consumer, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ClaimEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimEvent'
type Repository_ClaimEvent_Call struct {
	*mock.Call
}

// ClaimEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - consumer string
//   - eventID string
func (_e *Repository_Expecter) ClaimEvent(ctx interface{}, consumer interface{}, eventID interface{}) *Repository_ClaimEvent_Call {
	return &Repository_ClaimEvent_Call{Call: _e.mock.On("ClaimEvent", ctx, consumer, eventID)}
}

func (_c *Repository_ClaimEvent_Call) Run(run func(ctx context.Context, consumer string, eventID string)) *Repository_ClaimEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_ClaimEvent_Call) Return(_a0 bool, _a1 error) *Repository_ClaimEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ClaimEvent_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *Repository_ClaimEvent_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureUserProfile provides a mock function with given fields: ctx, userID
func (_m *Repository) EnsureUserProfile(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for EnsureUserProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_EnsureUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureUserProfile'
type Repository_EnsureUserProfile_Call struct {
	*mock.Call
}

// EnsureUserProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Repository_Expecter) EnsureUserProfile(ctx interface{}, userID interface{}) *Repository_EnsureUserProfile_Call {
	return &Repository_EnsureUserProfile_Call{Call: _e.mock.On("EnsureUserProfile", ctx, userID)}
}

func (_c *Repository_EnsureUserProfile_Call) Run(run func(ctx context.Context, userID string)) *Repository_EnsureUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_EnsureUserProfile_Call) Return(_a0 error) *Repository_EnsureUserProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_EnsureUserProfile_Call) RunAndReturn(run func(context.Context, string) error) *Repository_EnsureUserProfile_Call {
	_c.Call.Return(run)
	return _c
}

// FetchDashboardSnapshot provides a mock function with given fields: ctx, userID
func (_m *Repository) FetchDashboardSnapshot(ctx context.Context, userID string) (*model.DashboardSnapshot, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FetchDashboardSnapshot")
	}

	var r0 *model.DashboardSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.DashboardSnapshot, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.DashboardSnapshot); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DashboardSnapshot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FetchDashboardSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchDashboardSnapshot'
type Repository_FetchDashboardSnapshot_Call struct {
	*mock.Call
}

// FetchDashboardSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Repository_Expecter) FetchDashboardSnapshot(ctx interface{}, userID interface{}) *Repository_FetchDashboardSnapshot_Call {
	return &Repository_FetchDashboardSnapshot_Call{Call: _e.mock.On("FetchDashboardSnapshot", ctx, userID)}
}

func (_c *Repository_FetchDashboardSnapshot_Call) Run(run func(ctx context.Context, userID string)) *Repository_FetchDashboardSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_FetchDashboardSnapshot_Call) Return(_a0 *model.DashboardSnapshot, _a1 error) *Repository_FetchDashboardSnapshot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FetchDashboardSnapshot_Call) RunAndReturn(run func(context.Context, string) (*model.DashboardSnapshot, error)) *Repository_FetchDashboardSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecommendation provides a mock function with given fields: ctx, userID, id
func (_m *Repository) GetRecommendation(ctx context.Context, userID string, id string) (*model.Recommendation, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRecommendation")
	}

	var r0 *model.Recommendation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Recommendation, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Recommendation); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Recommendation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetRecommendation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecommendation'
type Repository_GetRecommendation_Call struct {
	*mock.Call
}

// GetRecommendation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *Repository_Expecter) GetRecommendation(ctx interface{}, userID interface{}, id interface{}) *Repository_GetRecommendation_Call {
	return &Repository_GetRecommendation_Call{Call: _e.mock.On("GetRecommendation", ctx, userID, id)}
}

func (_c *Repository_GetRecommendation_Call) Run(run func(ctx context.Context, userID string, id string)) *Repository_GetRecommendation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_GetRecommendation_Call) Return(_a0 *model.Recommendation, _a1 error) *Repository_GetRecommendation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetRecommendation_Call) RunAndReturn(run func(context.Context, string, string) (*model.Recommendation, error)) *Repository_GetRecommendation_Call {
	_c.Call.Return(run)
	return _c
}

// GetSkillScore provides a mock function with given fields: ctx, userID, skillKey
func (_m *Repository) GetSkillScore(ctx context.Context, userID string, skillKey string) (*model.SkillScore, error) {
	ret := _m.Called(ctx, userID, skillKey)

	if len(ret) == 0 {
		panic("no return value specified for GetSkillScore")
	}

	var r0 *model.SkillScore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.SkillScore, error)); ok {
		return rf(ctx, userID, skillKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.SkillScore); ok {
		r0 = rf(ctx, userID, skillKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SkillScore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, skillKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetSkillScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSkillScore'
type Repository_GetSkillScore_Call struct {
	*mock.Call
}

// GetSkillScore is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - skillKey string
func (_e *Repository_Expecter) GetSkillScore(ctx interface{}, userID interface{}, skillKey interface{}) *Repository_GetSkillScore_Call {
	return &Repository_GetSkillScore_Call{Call: _e.mock.On("GetSkillScore", ctx, userID, skillKey)}
}

func (_c *Repository_GetSkillScore_Call) Run(run func(ctx context.Context, userID string, skillKey string)) *Repository_GetSkillScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_GetSkillScore_Call) Return(_a0 *model.SkillScore, _a1 error) *Repository_GetSkillScore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetSkillScore_Call) RunAndReturn(run func(context.Context, string, string) (*model.SkillScore, error)) *Repository_GetSkillScore_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserProfile provides a mock function with given fields: ctx, userID
func (_m *Repository) GetUserProfile(ctx context.Context, userID string) (*model.UserSkillProfile, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserProfile")
	}

	var r0 *model.UserSkillProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserSkillProfile, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserSkillProfile); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserSkillProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserProfile'
type Repository_GetUserProfile_Call struct {
	*mock.Call
}

// GetUserProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Repository_Expecter) GetUserProfile(ctx interface{}, userID interface{}) *Repository_GetUserProfile_Call {
	return &Repository_GetUserProfile_Call{Call: _e.mock.On("GetUserProfile", ctx, userID)}
}

func (_c *Repository_GetUserProfile_Call) Run(run func(ctx context.Context, userID string)) *Repository_GetUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_GetUserProfile_Call) Return(_a0 *model.UserSkillProfile, _a1 error) *Repository_GetUserProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetUserProfile_Call) RunAndReturn(run func(context.Context, string) (*model.UserSkillProfile, error)) *Repository_GetUserProfile_Call {
	_c.Call.Return(run)
	return _c
}

// InsertSpecialRecommendation provides a mock function with given fields: ctx, rec
func (_m *Repository) InsertSpecialRecommendation(ctx context.Context, rec model.Recommendation) (*model.Recommendation, error) {
	ret := _m.Called(ctx, rec)

	if len(ret) == 0 {
		panic("no return value specified for InsertSpecialRecommendation")
	}

	var r0 *model.Recommendation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Recommendation) (*model.Recommendation, error)); ok {
		return rf(ctx, rec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Recommendation) *model.Recommendation); ok {
		r0 = rf(ctx, rec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Recommendation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Recommendation) error); ok {
		r1 = rf(ctx, rec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_InsertSpecialRecommendation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertSpecialRecommendation'
type Repository_InsertSpecialRecommendation_Call struct {
	*mock.Call
}

// InsertSpecialRecommendation is a helper method to define mock.On call
//   - ctx context.Context
//   - rec model.Recommendation
func (_e *Repository_Expecter) InsertSpecialRecommendation(ctx interface{}, rec interface{}) *Repository_InsertSpecialRecommendation_Call {
	return &Repository_InsertSpecialRecommendation_Call{Call: _e.mock.On("InsertSpecialRecommendation", ctx, rec)}
}

func (_c *Repository_InsertSpecialRecommendation_Call) Run(run func(ctx context.Context, rec model.Recommendation)) *Repository_InsertSpecialRecommendation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Recommendation))
	})
	return _c
}

func (_c *Repository_InsertSpecialRecommendation_Call) Return(_a0 *model.Recommendation, _a1 error) *Repository_InsertSpecialRecommendation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_InsertSpecialRecommendation_Call) RunAndReturn(run func(context.Context, model.Recommendation) (*model.Recommendation, error)) *Repository_InsertSpecialRecommendation_Call {
	_c.Call.Return(run)
	return _c
}

// InsertTakeMockRecommendation provides a mock function with given fields: ctx, rec
func (_m *Repository) InsertTakeMockRecommendation(ctx context.Context, rec model.Recommendation) (*model.Recommendation, error) {
	ret := _m.Called(ctx, rec)

	if len(ret) == 0 {
		panic("no return value specified for InsertTakeMockRecommendation")
	}

	var r0 *model.Recommendation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Recommendation) (*model.Recommendation, error)); ok {
		return rf(ctx, rec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Recommendation) *model.Recommendation); ok {
		r0 = rf(ctx, rec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Recommendation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Recommendation) error); ok {
		r1 = rf(ctx, rec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_InsertTakeMockRecommendation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertTakeMockRecommendation'
type Repository_InsertTakeMockRecommendation_Call struct {
	*mock.Call
}

// InsertTakeMockRecommendation is a helper method to define mock.On call
//   - ctx context.Context
//   - rec model.Recommendation
func (_e *Repository_Expecter) InsertTakeMockRecommendation(ctx interface{}, rec interface{}) *Repository_InsertTakeMockRecommendation_Call {
	return &Repository_InsertTakeMockRecommendation_Call{Call: _e.mock.On("InsertTakeMockRecommendation", ctx, rec)}
}

func (_c *Repository_InsertTakeMockRecommendation_Call) Run(run func(ctx context.Context, rec model.Recommendation)) *Repository_InsertTakeMockRecommendation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Recommendation))
	})
	return _c
}

func (_c *Repository_InsertTakeMockRecommendation_Call) Return(_a0 *model.Recommendation, _a1 error) *Repository_InsertTakeMockRecommendation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_InsertTakeMockRecommendation_Call) RunAndReturn(run func(context.Context, model.Recommendation) (*model.Recommendation, error)) *Repository_InsertTakeMockRecommendation_Call {
	_c.Call.Return(run)
	return _c
}

// IsEventProcessed provides a mock function with given fields: ctx, consumer, eventID
func (_m *Repository) IsEventProcessed(ctx context.Context, consumer string, eventID string) (bool, error) {
	ret := _m.Called(ctx, consumer, eventID)

	if len(ret) == 0 {
		panic("no return value specified for IsEventProcessed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, consumer, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, consumer, eventID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, consumer, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_IsEventProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEventProcessed'
type Repository_IsEventProcessed_Call struct {
	*mock.Call
}

// IsEventProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - consumer string
//   - eventID string
func (_e *Repository_Expecter) IsEventProcessed(ctx interface{}, consumer interface{}, eventID interface{}) *Repository_IsEventProcessed_Call {
	return &Repository_IsEventProcessed_Call{Call: _e.mock.On("IsEventProcessed", ctx, consumer, eventID)}
}

func (_c *Repository_IsEventProcessed_Call) Run(run func(ctx context.Context, consumer string, eventID string)) *Repository_IsEventProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_IsEventProcessed_Call) Return(_a0 bool, _a1 error) *Repository_IsEventProcessed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_IsEventProcessed_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *Repository_IsEventProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveRecommendations provides a mock function with given fields: ctx, userID
func (_m *Repository) ListActiveRecommendations(ctx context.Context, userID string) ([]model.Recommendation, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveRecommendations")
	}

	var r0 []model.Recommendation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Recommendation, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Recommendation); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Recommendation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListActiveRecommendations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveRecommendations'
type Repository_ListActiveRecommendations_Call struct {
	*mock.Call
}

// ListActiveRecommendations is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Repository_Expecter) ListActiveRecommendations(ctx interface{}, userID interface{}) *Repository_ListActiveRecommendations_Call {
	return &Repository_ListActiveRecommendations_Call{Call: _e.mock.On("ListActiveRecommendations", ctx, userID)}
}

func (_c *Repository_ListActiveRecommendations_Call) Run(run func(ctx context.Context, userID string)) *Repository_ListActiveRecommendations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_ListActiveRecommendations_Call) Return(_a0 []model.Recommendation, _a1 error) *Repository_ListActiveRecommendations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListActiveRecommendations_Call) RunAndReturn(run func(context.Context, string) ([]model.Recommendation, error)) *Repository_ListActiveRecommendations_Call {
	_c.Call.Return(run)
	return _c
}

// ListArticleReadSlugs provides a mock function with given fields: ctx, userID
func (_m *Repository) ListArticleReadSlugs(ctx context.Context, userID string) ([]string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListArticleReadSlugs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListArticleReadSlugs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListArticleReadSlugs'
type Repository_ListArticleReadSlugs_Call struct {
	*mock.Call
}

// ListArticleReadSlugs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Repository_Expecter) ListArticleReadSlugs(ctx interface{}, userID interface{}) *Repository_ListArticleReadSlugs_Call {
	return &Repository_ListArticleReadSlugs_Call{Call: _e.mock.On("ListArticleReadSlugs", ctx, userID)}
}

func (_c *Repository_ListArticleReadSlugs_Call) Run(run func(ctx context.Context, userID string)) *Repository_ListArticleReadSlugs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_ListArticleReadSlugs_Call) Return(_a0 []string, _a1 error) *Repository_ListArticleReadSlugs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListArticleReadSlugs_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *Repository_ListArticleReadSlugs_Call {
	_c.Call.Return(run)
	return _c
}

// ListPassedTaskIDsByType provides a mock function with given fields: ctx, userID, taskType
func (_m *Repository) ListPassedTaskIDsByType(ctx context.Context, userID string, taskType string) ([]string, error) {
	ret := _m.Called(ctx, userID, taskType)

	if len(ret) == 0 {
		panic("no return value specified for ListPassedTaskIDsByType")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return rf(ctx, userID, taskType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = rf(ctx, userID, taskType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, taskType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListPassedTaskIDsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPassedTaskIDsByType'
type Repository_ListPassedTaskIDsByType_Call struct {
	*mock.Call
}

// ListPassedTaskIDsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - taskType string
func (_e *Repository_Expecter) ListPassedTaskIDsByType(ctx interface{}, userID interface{}, taskType interface{}) *Repository_ListPassedTaskIDsByType_Call {
	return &Repository_ListPassedTaskIDsByType_Call{Call: _e.mock.On("ListPassedTaskIDsByType", ctx, userID, taskType)}
}

func (_c *Repository_ListPassedTaskIDsByType_Call) Run(run func(ctx context.Context, userID string, taskType string)) *Repository_ListPassedTaskIDsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_ListPassedTaskIDsByType_Call) Return(_a0 []string, _a1 error) *Repository_ListPassedTaskIDsByType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListPassedTaskIDsByType_Call) RunAndReturn(run func(context.Context, string, string) ([]string, error)) *Repository_ListPassedTaskIDsByType_Call {
	_c.Call.Return(run)
	return _c
}

// ListPracticeModeActivity provides a mock function with given fields: ctx, userID
func (_m *Repository) ListPracticeModeActivity(ctx context.Context, userID string) ([]model.UserPracticeModeActivity, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListPracticeModeActivity")
	}

	var r0 []model.UserPracticeModeActivity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.UserPracticeModeActivity, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.UserPracticeModeActivity); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserPracticeModeActivity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListPracticeModeActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPracticeModeActivity'
type Repository_ListPracticeModeActivity_Call struct {
	*mock.Call
}

// ListPracticeModeActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Repository_Expecter) ListPracticeModeActivity(ctx interface{}, userID interface{}) *Repository_ListPracticeModeActivity_Call {
	return &Repository_ListPracticeModeActivity_Call{Call: _e.mock.On("ListPracticeModeActivity", ctx, userID)}
}

func (_c *Repository_ListPracticeModeActivity_Call) Run(run func(ctx context.Context, userID string)) *Repository_ListPracticeModeActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_ListPracticeModeActivity_Call) Return(_a0 []model.UserPracticeModeActivity, _a1 error) *Repository_ListPracticeModeActivity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListPracticeModeActivity_Call) RunAndReturn(run func(context.Context, string) ([]model.UserPracticeModeActivity, error)) *Repository_ListPracticeModeActivity_Call {
	_c.Call.Return(run)
	return _c
}

// ListReviewTaskCandidates provides a mock function with given fields: ctx, userID, taskType, staleAfter, limit
func (_m *Repository) ListReviewTaskCandidates(ctx context.Context, userID string, taskType string, staleAfter time.Time, limit int) ([]model.ReviewTaskCandidate, error) {
	ret := _m.Called(ctx, userID, taskType, staleAfter, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListReviewTaskCandidates")
	}

	var r0 []model.ReviewTaskCandidate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, int) ([]model.ReviewTaskCandidate, error)); ok {
		return rf(ctx, userID, taskType, staleAfter, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, int) []model.ReviewTaskCandidate); ok {
		r0 = rf(ctx, userID, taskType, staleAfter, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ReviewTaskCandidate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time, int) error); ok {
		r1 = rf(ctx, userID, taskType, staleAfter, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListReviewTaskCandidates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReviewTaskCandidates'
type Repository_ListReviewTaskCandidates_Call struct {
	*mock.Call
}

// ListReviewTaskCandidates is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - taskType string
//   - staleAfter time.Time
//   - limit int
func (_e *Repository_Expecter) ListReviewTaskCandidates(ctx interface{}, userID interface{}, taskType interface{}, staleAfter interface{}, limit interface{}) *Repository_ListReviewTaskCandidates_Call {
	return &Repository_ListReviewTaskCandidates_Call{Call: _e.mock.On("ListReviewTaskCandidates", ctx, userID, taskType, staleAfter, limit)}
}

func (_c *Repository_ListReviewTaskCandidates_Call) Run(run func(ctx context.Context, userID string, taskType string, staleAfter time.Time, limit int)) *Repository_ListReviewTaskCandidates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time), args[4].(int))
	})
	return _c
}

func (_c *Repository_ListReviewTaskCandidates_Call) Return(_a0 []model.ReviewTaskCandidate, _a1 error) *Repository_ListReviewTaskCandidates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListReviewTaskCandidates_Call) RunAndReturn(run func(context.Context, string, string, time.Time, int) ([]model.ReviewTaskCandidate, error)) *Repository_ListReviewTaskCandidates_Call {
	_c.Call.Return(run)
	return _c
}

// ListSkillScoresByUser provides a mock function with given fields: ctx, userID
func (_m *Repository) ListSkillScoresByUser(ctx context.Context, userID string) ([]model.SkillScore, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListSkillScoresByUser")
	}

	var r0 []model.SkillScore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.SkillScore, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.SkillScore); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SkillScore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListSkillScoresByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSkillScoresByUser'
type Repository_ListSkillScoresByUser_Call struct {
	*mock.Call
}

// ListSkillScoresByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Repository_Expecter) ListSkillScoresByUser(ctx interface{}, userID interface{}) *Repository_ListSkillScoresByUser_Call {
	return &Repository_ListSkillScoresByUser_Call{Call: _e.mock.On("ListSkillScoresByUser", ctx, userID)}
}

func (_c *Repository_ListSkillScoresByUser_Call) Run(run func(ctx context.Context, userID string)) *Repository_ListSkillScoresByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_ListSkillScoresByUser_Call) Return(_a0 []model.SkillScore, _a1 error) *Repository_ListSkillScoresByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListSkillScoresByUser_Call) RunAndReturn(run func(context.Context, string) ([]model.SkillScore, error)) *Repository_ListSkillScoresByUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListTaskTypeCoverage provides a mock function with given fields: ctx, userID
func (_m *Repository) ListTaskTypeCoverage(ctx context.Context, userID string) ([]model.TaskTypeCoverage, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListTaskTypeCoverage")
	}

	var r0 []model.TaskTypeCoverage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.TaskTypeCoverage, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.TaskTypeCoverage); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.TaskTypeCoverage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListTaskTypeCoverage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTaskTypeCoverage'
type Repository_ListTaskTypeCoverage_Call struct {
	*mock.Call
}

// ListTaskTypeCoverage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Repository_Expecter) ListTaskTypeCoverage(ctx interface{}, userID interface{}) *Repository_ListTaskTypeCoverage_Call {
	return &Repository_ListTaskTypeCoverage_Call{Call: _e.mock.On("ListTaskTypeCoverage", ctx, userID)}
}

func (_c *Repository_ListTaskTypeCoverage_Call) Run(run func(ctx context.Context, userID string)) *Repository_ListTaskTypeCoverage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_ListTaskTypeCoverage_Call) Return(_a0 []model.TaskTypeCoverage, _a1 error) *Repository_ListTaskTypeCoverage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListTaskTypeCoverage_Call) RunAndReturn(run func(context.Context, string) ([]model.TaskTypeCoverage, error)) *Repository_ListTaskTypeCoverage_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserTemplateProgress provides a mock function with given fields: ctx, userID
func (_m *Repository) ListUserTemplateProgress(ctx context.Context, userID string) ([]model.UserTemplateProgress, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserTemplateProgress")
	}

	var r0 []model.UserTemplateProgress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.UserTemplateProgress, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.UserTemplateProgress); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserTemplateProgress)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListUserTemplateProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserTemplateProgress'
type Repository_ListUserTemplateProgress_Call struct {
	*mock.Call
}

// ListUserTemplateProgress is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Repository_Expecter) ListUserTemplateProgress(ctx interface{}, userID interface{}) *Repository_ListUserTemplateProgress_Call {
	return &Repository_ListUserTemplateProgress_Call{Call: _e.mock.On("ListUserTemplateProgress", ctx, userID)}
}

func (_c *Repository_ListUserTemplateProgress_Call) Run(run func(ctx context.Context, userID string)) *Repository_ListUserTemplateProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_ListUserTemplateProgress_Call) Return(_a0 []model.UserTemplateProgress, _a1 error) *Repository_ListUserTemplateProgress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListUserTemplateProgress_Call) RunAndReturn(run func(context.Context, string) ([]model.UserTemplateProgress, error)) *Repository_ListUserTemplateProgress_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateReadinessScore provides a mock function with given fields: ctx, userID, readiness
func (_m *Repository) UpdateReadinessScore(ctx context.Context, userID string, readiness int) error {
	ret := _m.Called(ctx, userID, readiness)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReadinessScore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, userID, readiness)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateReadinessScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReadinessScore'
type Repository_UpdateReadinessScore_Call struct {
	*mock.Call
}

// UpdateReadinessScore is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - readiness int
func (_e *Repository_Expecter) UpdateReadinessScore(ctx interface{}, userID interface{}, readiness interface{}) *Repository_UpdateReadinessScore_Call {
	return &Repository_UpdateReadinessScore_Call{Call: _e.mock.On("UpdateReadinessScore", ctx, userID, readiness)}
}

func (_c *Repository_UpdateReadinessScore_Call) Run(run func(ctx context.Context, userID string, readiness int)) *Repository_UpdateReadinessScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *Repository_UpdateReadinessScore_Call) Return(_a0 error) *Repository_UpdateReadinessScore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateReadinessScore_Call) RunAndReturn(run func(context.Context, string, int) error) *Repository_UpdateReadinessScore_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRecommendationStatus provides a mock function with given fields: ctx, userID, id, status
func (_m *Repository) UpdateRecommendationStatus(ctx context.Context, userID string, id string, status model.RecommendationStatus) error {
	ret := _m.Called(ctx, userID, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRecommendationStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.RecommendationStatus) error); ok {
		r0 = rf(ctx, userID, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateRecommendationStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRecommendationStatus'
type Repository_UpdateRecommendationStatus_Call struct {
	*mock.Call
}

// UpdateRecommendationStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
//   - status model.RecommendationStatus
func (_e *Repository_Expecter) UpdateRecommendationStatus(ctx interface{}, userID interface{}, id interface{}, status interface{}) *Repository_UpdateRecommendationStatus_Call {
	return &Repository_UpdateRecommendationStatus_Call{Call: _e.mock.On("UpdateRecommendationStatus", ctx, userID, id, status)}
}

func (_c *Repository_UpdateRecommendationStatus_Call) Run(run func(ctx context.Context, userID string, id string, status model.RecommendationStatus)) *Repository_UpdateRecommendationStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(model.RecommendationStatus))
	})
	return _c
}

func (_c *Repository_UpdateRecommendationStatus_Call) Return(_a0 error) *Repository_UpdateRecommendationStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateRecommendationStatus_Call) RunAndReturn(run func(context.Context, string, string, model.RecommendationStatus) error) *Repository_UpdateRecommendationStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertArticleRead provides a mock function with given fields: ctx, userID, slug
func (_m *Repository) UpsertArticleRead(ctx context.Context, userID string, slug string) (*model.ArticleRead, error) {
	ret := _m.Called(ctx, userID, slug)

	if len(ret) == 0 {
		panic("no return value specified for UpsertArticleRead")
	}

	var r0 *model.ArticleRead
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.ArticleRead, error)); ok {
		return rf(ctx, userID, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.ArticleRead); ok {
		r0 = rf(ctx, userID, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ArticleRead)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_UpsertArticleRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertArticleRead'
type Repository_UpsertArticleRead_Call struct {
	*mock.Call
}

// UpsertArticleRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - slug string
func (_e *Repository_Expecter) UpsertArticleRead(ctx interface{}, userID interface{}, slug interface{}) *Repository_UpsertArticleRead_Call {
	return &Repository_UpsertArticleRead_Call{Call: _e.mock.On("UpsertArticleRead", ctx, userID, slug)}
}

func (_c *Repository_UpsertArticleRead_Call) Run(run func(ctx context.Context, userID string, slug string)) *Repository_UpsertArticleRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_UpsertArticleRead_Call) Return(_a0 *model.ArticleRead, _a1 error) *Repository_UpsertArticleRead_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_UpsertArticleRead_Call) RunAndReturn(run func(context.Context, string, string) (*model.ArticleRead, error)) *Repository_UpsertArticleRead_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertImproveSkillRecommendation provides a mock function with given fields: ctx, rec
func (_m *Repository) UpsertImproveSkillRecommendation(ctx context.Context, rec model.Recommendation) (*model.Recommendation, error) {
	ret := _m.Called(ctx, rec)

	if len(ret) == 0 {
		panic("no return value specified for UpsertImproveSkillRecommendation")
	}

	var r0 *model.Recommendation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Recommendation) (*model.Recommendation, error)); ok {
		return rf(ctx, rec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Recommendation) *model.Recommendation); ok {
		r0 = rf(ctx, rec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Recommendation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Recommendation) error); ok {
		r1 = rf(ctx, rec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_UpsertImproveSkillRecommendation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertImproveSkillRecommendation'
type Repository_UpsertImproveSkillRecommendation_Call struct {
	*mock.Call
}

// UpsertImproveSkillRecommendation is a helper method to define mock.On call
//   - ctx context.Context
//   - rec model.Recommendation
func (_e *Repository_Expecter) UpsertImproveSkillRecommendation(ctx interface{}, rec interface{}) *Repository_UpsertImproveSkillRecommendation_Call {
	return &Repository_UpsertImproveSkillRecommendation_Call{Call: _e.mock.On("UpsertImproveSkillRecommendation", ctx, rec)}
}

func (_c *Repository_UpsertImproveSkillRecommendation_Call) Run(run func(ctx context.Context, rec model.Recommendation)) *Repository_UpsertImproveSkillRecommendation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Recommendation))
	})
	return _c
}

func (_c *Repository_UpsertImproveSkillRecommendation_Call) Return(_a0 *model.Recommendation, _a1 error) *Repository_UpsertImproveSkillRecommendation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_UpsertImproveSkillRecommendation_Call) RunAndReturn(run func(context.Context, model.Recommendation) (*model.Recommendation, error)) *Repository_UpsertImproveSkillRecommendation_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertPracticeModeActivity provides a mock function with given fields: ctx, userID, sessionMode, taskType, passed, seenAt
func (_m *Repository) UpsertPracticeModeActivity(ctx context.Context, userID string, sessionMode string, taskType string, passed bool, seenAt time.Time) error {
	ret := _m.Called(ctx, userID, sessionMode, taskType, passed, seenAt)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPracticeModeActivity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool, time.Time) error); ok {
		r0 = rf(ctx, userID, sessionMode, taskType, passed, seenAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpsertPracticeModeActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertPracticeModeActivity'
type Repository_UpsertPracticeModeActivity_Call struct {
	*mock.Call
}

// UpsertPracticeModeActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - sessionMode string
//   - taskType string
//   - passed bool
//   - seenAt time.Time
func (_e *Repository_Expecter) UpsertPracticeModeActivity(ctx interface{}, userID interface{}, sessionMode interface{}, taskType interface{}, passed interface{}, seenAt interface{}) *Repository_UpsertPracticeModeActivity_Call {
	return &Repository_UpsertPracticeModeActivity_Call{Call: _e.mock.On("UpsertPracticeModeActivity", ctx, userID, sessionMode, taskType, passed, seenAt)}
}

func (_c *Repository_UpsertPracticeModeActivity_Call) Run(run func(ctx context.Context, userID string, sessionMode string, taskType string, passed bool, seenAt time.Time)) *Repository_UpsertPracticeModeActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(bool), args[5].(time.Time))
	})
	return _c
}

func (_c *Repository_UpsertPracticeModeActivity_Call) Return(_a0 error) *Repository_UpsertPracticeModeActivity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpsertPracticeModeActivity_Call) RunAndReturn(run func(context.Context, string, string, string, bool, time.Time) error) *Repository_UpsertPracticeModeActivity_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertSkillScore provides a mock function with given fields: ctx, userID, skillKey, normalized, seenAt
func (_m *Repository) UpsertSkillScore(ctx context.Context, userID string, skillKey string, normalized int, seenAt time.Time) (*model.SkillScore, error) {
	ret := _m.Called(ctx, userID, skillKey, normalized, seenAt)

	if len(ret) == 0 {
		panic("no return value specified for UpsertSkillScore")
	}

	var r0 *model.SkillScore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, time.Time) (*model.SkillScore, error)); ok {
		return rf(ctx, userID, skillKey, normalized, seenAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, time.Time) *model.SkillScore); ok {
		r0 = rf(ctx, userID, skillKey, normalized, seenAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SkillScore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, time.Time) error); ok {
		r1 = rf(ctx, userID, skillKey, normalized, seenAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_UpsertSkillScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertSkillScore'
type Repository_UpsertSkillScore_Call struct {
	*mock.Call
}

// UpsertSkillScore is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - skillKey string
//   - normalized int
//   - seenAt time.Time
func (_e *Repository_Expecter) UpsertSkillScore(ctx interface{}, userID interface{}, skillKey interface{}, normalized interface{}, seenAt interface{}) *Repository_UpsertSkillScore_Call {
	return &Repository_UpsertSkillScore_Call{Call: _e.mock.On("UpsertSkillScore", ctx, userID, skillKey, normalized, seenAt)}
}

func (_c *Repository_UpsertSkillScore_Call) Run(run func(ctx context.Context, userID string, skillKey string, normalized int, seenAt time.Time)) *Repository_UpsertSkillScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(time.Time))
	})
	return _c
}

func (_c *Repository_UpsertSkillScore_Call) Return(_a0 *model.SkillScore, _a1 error) *Repository_UpsertSkillScore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_UpsertSkillScore_Call) RunAndReturn(run func(context.Context, string, string, int, time.Time) (*model.SkillScore, error)) *Repository_UpsertSkillScore_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertUserTaskProgress provides a mock function with given fields: ctx, userID, taskID, taskType, score, passed, seenAt
func (_m *Repository) UpsertUserTaskProgress(ctx context.Context, userID string, taskID string, taskType string, score int, passed bool, seenAt time.Time) error {
	ret := _m.Called(ctx, userID, taskID, taskType, score, passed, seenAt)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUserTaskProgress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, bool, time.Time) error); ok {
		r0 = rf(ctx, userID, taskID, taskType, score, passed, seenAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpsertUserTaskProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUserTaskProgress'
type Repository_UpsertUserTaskProgress_Call struct {
	*mock.Call
}

// UpsertUserTaskProgress is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - taskID string
//   - taskType string
//   - score int
//   - passed bool
//   - seenAt time.Time
func (_e *Repository_Expecter) UpsertUserTaskProgress(ctx interface{}, userID interface{}, taskID interface{}, taskType interface{}, score interface{}, passed interface{}, seenAt interface{}) *Repository_UpsertUserTaskProgress_Call {
	return &Repository_UpsertUserTaskProgress_Call{Call: _e.mock.On("UpsertUserTaskProgress", ctx, userID, taskID, taskType, score, passed, seenAt)}
}

func (_c *Repository_UpsertUserTaskProgress_Call) Run(run func(ctx context.Context, userID string, taskID string, taskType string, score int, passed bool, seenAt time.Time)) *Repository_UpsertUserTaskProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(int), args[5].(bool), args[6].(time.Time))
	})
	return _c
}

func (_c *Repository_UpsertUserTaskProgress_Call) Return(_a0 error) *Repository_UpsertUserTaskProgress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpsertUserTaskProgress_Call) RunAndReturn(run func(context.Context, string, string, string, int, bool, time.Time) error) *Repository_UpsertUserTaskProgress_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertUserTemplateProgress provides a mock function with given fields: ctx, userID, templateID, sessionID, totalScore, passingScore, seenAt
func (_m *Repository) UpsertUserTemplateProgress(ctx context.Context, userID string, templateID string, sessionID string, totalScore int, passingScore int, seenAt time.Time) error {
	ret := _m.Called(ctx, userID, templateID, sessionID, totalScore, passingScore, seenAt)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUserTemplateProgress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, int, time.Time) error); ok {
		r0 = rf(ctx, userID, templateID, sessionID, totalScore, passingScore, seenAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpsertUserTemplateProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUserTemplateProgress'
type Repository_UpsertUserTemplateProgress_Call struct {
	*mock.Call
}

// UpsertUserTemplateProgress is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - templateID string
//   - sessionID string
//   - totalScore int
//   - passingScore int
//   - seenAt time.Time
func (_e *Repository_Expecter) UpsertUserTemplateProgress(ctx interface{}, userID interface{}, templateID interface{}, sessionID interface{}, totalScore interface{}, passingScore interface{}, seenAt interface{}) *Repository_UpsertUserTemplateProgress_Call {
	return &Repository_UpsertUserTemplateProgress_Call{Call: _e.mock.On("UpsertUserTemplateProgress", ctx, userID, templateID, sessionID, totalScore, passingScore, seenAt)}
}

func (_c *Repository_UpsertUserTemplateProgress_Call) Run(run func(ctx context.Context, userID string, templateID string, sessionID string, totalScore int, passingScore int, seenAt time.Time)) *Repository_UpsertUserTemplateProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(int), args[5].(int), args[6].(time.Time))
	})
	return _c
}

func (_c *Repository_UpsertUserTemplateProgress_Call) Return(_a0 error) *Repository_UpsertUserTemplateProgress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpsertUserTemplateProgress_Call) RunAndReturn(run func(context.Context, string, string, string, int, int, time.Time) error) *Repository_UpsertUserTemplateProgress_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function with given fields: ctx, fn
func (_m *Repository) WithTx(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type Repository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *Repository_Expecter) WithTx(ctx interface{}, fn interface{}) *Repository_WithTx_Call {
	return &Repository_WithTx_Call{Call: _e.mock.On("WithTx", ctx, fn)}
}

func (_c *Repository_WithTx_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *Repository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *Repository_WithTx_Call) Return(_a0 error) *Repository_WithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_WithTx_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *Repository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
