// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/sedorofeevd/project-druzya/services/recommendation/internal/recommendation/model"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CompleteLearningPlanItem provides a mock function with given fields: ctx, userID, id
func (_m *Service) CompleteLearningPlanItem(ctx context.Context, userID string, id string) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for CompleteLearningPlanItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_CompleteLearningPlanItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteLearningPlanItem'
type Service_CompleteLearningPlanItem_Call struct {
	*mock.Call
}

// CompleteLearningPlanItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *Service_Expecter) CompleteLearningPlanItem(ctx interface{}, userID interface{}, id interface{}) *Service_CompleteLearningPlanItem_Call {
	return &Service_CompleteLearningPlanItem_Call{Call: _e.mock.On("CompleteLearningPlanItem", ctx, userID, id)}
}

func (_c *Service_CompleteLearningPlanItem_Call) Run(run func(ctx context.Context, userID string, id string)) *Service_CompleteLearningPlanItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Service_CompleteLearningPlanItem_Call) Return(_a0 error) *Service_CompleteLearningPlanItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_CompleteLearningPlanItem_Call) RunAndReturn(run func(context.Context, string, string) error) *Service_CompleteLearningPlanItem_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteRecommendation provides a mock function with given fields: ctx, userID, id
func (_m *Service) CompleteRecommendation(ctx context.Context, userID string, id string) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for CompleteRecommendation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_CompleteRecommendation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteRecommendation'
type Service_CompleteRecommendation_Call struct {
	*mock.Call
}

// CompleteRecommendation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *Service_Expecter) CompleteRecommendation(ctx interface{}, userID interface{}, id interface{}) *Service_CompleteRecommendation_Call {
	return &Service_CompleteRecommendation_Call{Call: _e.mock.On("CompleteRecommendation", ctx, userID, id)}
}

func (_c *Service_CompleteRecommendation_Call) Run(run func(ctx context.Context, userID string, id string)) *Service_CompleteRecommendation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Service_CompleteRecommendation_Call) Return(_a0 error) *Service_CompleteRecommendation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_CompleteRecommendation_Call) RunAndReturn(run func(context.Context, string, string) error) *Service_CompleteRecommendation_Call {
	_c.Call.Return(run)
	return _c
}

// DismissLearningPlanItem provides a mock function with given fields: ctx, userID, id
func (_m *Service) DismissLearningPlanItem(ctx context.Context, userID string, id string) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DismissLearningPlanItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_DismissLearningPlanItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DismissLearningPlanItem'
type Service_DismissLearningPlanItem_Call struct {
	*mock.Call
}

// DismissLearningPlanItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *Service_Expecter) DismissLearningPlanItem(ctx interface{}, userID interface{}, id interface{}) *Service_DismissLearningPlanItem_Call {
	return &Service_DismissLearningPlanItem_Call{Call: _e.mock.On("DismissLearningPlanItem", ctx, userID, id)}
}

func (_c *Service_DismissLearningPlanItem_Call) Run(run func(ctx context.Context, userID string, id string)) *Service_DismissLearningPlanItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Service_DismissLearningPlanItem_Call) Return(_a0 error) *Service_DismissLearningPlanItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_DismissLearningPlanItem_Call) RunAndReturn(run func(context.Context, string, string) error) *Service_DismissLearningPlanItem_Call {
	_c.Call.Return(run)
	return _c
}

// DismissRecommendation provides a mock function with given fields: ctx, userID, id
func (_m *Service) DismissRecommendation(ctx context.Context, userID string, id string) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DismissRecommendation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_DismissRecommendation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DismissRecommendation'
type Service_DismissRecommendation_Call struct {
	*mock.Call
}

// DismissRecommendation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *Service_Expecter) DismissRecommendation(ctx interface{}, userID interface{}, id interface{}) *Service_DismissRecommendation_Call {
	return &Service_DismissRecommendation_Call{Call: _e.mock.On("DismissRecommendation", ctx, userID, id)}
}

func (_c *Service_DismissRecommendation_Call) Run(run func(ctx context.Context, userID string, id string)) *Service_DismissRecommendation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Service_DismissRecommendation_Call) Return(_a0 error) *Service_DismissRecommendation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_DismissRecommendation_Call) RunAndReturn(run func(context.Context, string, string) error) *Service_DismissRecommendation_Call {
	_c.Call.Return(run)
	return _c
}

// GetDashboard provides a mock function with given fields: ctx, userID
func (_m *Service) GetDashboard(ctx context.Context, userID string) (*model.Dashboard, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDashboard")
	}

	var r0 *model.Dashboard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Dashboard, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Dashboard); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Dashboard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetDashboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDashboard'
type Service_GetDashboard_Call struct {
	*mock.Call
}

// GetDashboard is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Service_Expecter) GetDashboard(ctx interface{}, userID interface{}) *Service_GetDashboard_Call {
	return &Service_GetDashboard_Call{Call: _e.mock.On("GetDashboard", ctx, userID)}
}

func (_c *Service_GetDashboard_Call) Run(run func(ctx context.Context, userID string)) *Service_GetDashboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Service_GetDashboard_Call) Return(_a0 *model.Dashboard, _a1 error) *Service_GetDashboard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetDashboard_Call) RunAndReturn(run func(context.Context, string) (*model.Dashboard, error)) *Service_GetDashboard_Call {
	_c.Call.Return(run)
	return _c
}

// HandleAttemptEvaluated provides a mock function with given fields: ctx, eventID, event
func (_m *Service) HandleAttemptEvaluated(ctx context.Context, eventID string, event model.AttemptEvaluatedEvent) error {
	ret := _m.Called(ctx, eventID, event)

	if len(ret) == 0 {
		panic("no return value specified for HandleAttemptEvaluated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.AttemptEvaluatedEvent) error); ok {
		r0 = rf(ctx, eventID, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_HandleAttemptEvaluated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleAttemptEvaluated'
type Service_HandleAttemptEvaluated_Call struct {
	*mock.Call
}

// HandleAttemptEvaluated is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - event model.AttemptEvaluatedEvent
func (_e *Service_Expecter) HandleAttemptEvaluated(ctx interface{}, eventID interface{}, event interface{}) *Service_HandleAttemptEvaluated_Call {
	return &Service_HandleAttemptEvaluated_Call{Call: _e.mock.On("HandleAttemptEvaluated", ctx, eventID, event)}
}

func (_c *Service_HandleAttemptEvaluated_Call) Run(run func(ctx context.Context, eventID string, event model.AttemptEvaluatedEvent)) *Service_HandleAttemptEvaluated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.AttemptEvaluatedEvent))
	})
	return _c
}

func (_c *Service_HandleAttemptEvaluated_Call) Return(_a0 error) *Service_HandleAttemptEvaluated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_HandleAttemptEvaluated_Call) RunAndReturn(run func(context.Context, string, model.AttemptEvaluatedEvent) error) *Service_HandleAttemptEvaluated_Call {
	_c.Call.Return(run)
	return _c
}

// HandleRetryItemCreated provides a mock function with given fields: ctx, eventID, event
func (_m *Service) HandleRetryItemCreated(ctx context.Context, eventID string, event model.RetryItemCreatedEvent) error {
	ret := _m.Called(ctx, eventID, event)

	if len(ret) == 0 {
		panic("no return value specified for HandleRetryItemCreated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.RetryItemCreatedEvent) error); ok {
		r0 = rf(ctx, eventID, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_HandleRetryItemCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleRetryItemCreated'
type Service_HandleRetryItemCreated_Call struct {
	*mock.Call
}

// HandleRetryItemCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - event model.RetryItemCreatedEvent
func (_e *Service_Expecter) HandleRetryItemCreated(ctx interface{}, eventID interface{}, event interface{}) *Service_HandleRetryItemCreated_Call {
	return &Service_HandleRetryItemCreated_Call{Call: _e.mock.On("HandleRetryItemCreated", ctx, eventID, event)}
}

func (_c *Service_HandleRetryItemCreated_Call) Run(run func(ctx context.Context, eventID string, event model.RetryItemCreatedEvent)) *Service_HandleRetryItemCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.RetryItemCreatedEvent))
	})
	return _c
}

func (_c *Service_HandleRetryItemCreated_Call) Return(_a0 error) *Service_HandleRetryItemCreated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_HandleRetryItemCreated_Call) RunAndReturn(run func(context.Context, string, model.RetryItemCreatedEvent) error) *Service_HandleRetryItemCreated_Call {
	_c.Call.Return(run)
	return _c
}

// HandleSessionCompleted provides a mock function with given fields: ctx, eventID, event
func (_m *Service) HandleSessionCompleted(ctx context.Context, eventID string, event model.SessionCompletedEvent) error {
	ret := _m.Called(ctx, eventID, event)

	if len(ret) == 0 {
		panic("no return value specified for HandleSessionCompleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.SessionCompletedEvent) error); ok {
		r0 = rf(ctx, eventID, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_HandleSessionCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleSessionCompleted'
type Service_HandleSessionCompleted_Call struct {
	*mock.Call
}

// HandleSessionCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - event model.SessionCompletedEvent
func (_e *Service_Expecter) HandleSessionCompleted(ctx interface{}, eventID interface{}, event interface{}) *Service_HandleSessionCompleted_Call {
	return &Service_HandleSessionCompleted_Call{Call: _e.mock.On("HandleSessionCompleted", ctx, eventID, event)}
}

func (_c *Service_HandleSessionCompleted_Call) Run(run func(ctx context.Context, eventID string, event model.SessionCompletedEvent)) *Service_HandleSessionCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.SessionCompletedEvent))
	})
	return _c
}

func (_c *Service_HandleSessionCompleted_Call) Return(_a0 error) *Service_HandleSessionCompleted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_HandleSessionCompleted_Call) RunAndReturn(run func(context.Context, string, model.SessionCompletedEvent) error) *Service_HandleSessionCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// HandleTaskSkipped provides a mock function with given fields: ctx, eventID, event
func (_m *Service) HandleTaskSkipped(ctx context.Context, eventID string, event model.TaskSkippedEvent) error {
	ret := _m.Called(ctx, eventID, event)

	if len(ret) == 0 {
		panic("no return value specified for HandleTaskSkipped")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.TaskSkippedEvent) error); ok {
		r0 = rf(ctx, eventID, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_HandleTaskSkipped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleTaskSkipped'
type Service_HandleTaskSkipped_Call struct {
	*mock.Call
}

// HandleTaskSkipped is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - event model.TaskSkippedEvent
func (_e *Service_Expecter) HandleTaskSkipped(ctx interface{}, eventID interface{}, event interface{}) *Service_HandleTaskSkipped_Call {
	return &Service_HandleTaskSkipped_Call{Call: _e.mock.On("HandleTaskSkipped", ctx, eventID, event)}
}

func (_c *Service_HandleTaskSkipped_Call) Run(run func(ctx context.Context, eventID string, event model.TaskSkippedEvent)) *Service_HandleTaskSkipped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.TaskSkippedEvent))
	})
	return _c
}

func (_c *Service_HandleTaskSkipped_Call) Return(_a0 error) *Service_HandleTaskSkipped_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_HandleTaskSkipped_Call) RunAndReturn(run func(context.Context, string, model.TaskSkippedEvent) error) *Service_HandleTaskSkipped_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
