// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/sedorofeevd/project-druzya/services/recommendation/internal/recommendation/model"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CompleteRecommendation provides a mock function with given fields: ctx, userID, id
func (_m *Service) CompleteRecommendation(ctx context.Context, userID string, id string) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for CompleteRecommendation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_CompleteRecommendation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteRecommendation'
type Service_CompleteRecommendation_Call struct {
	*mock.Call
}

// CompleteRecommendation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *Service_Expecter) CompleteRecommendation(ctx interface{}, userID interface{}, id interface{}) *Service_CompleteRecommendation_Call {
	return &Service_CompleteRecommendation_Call{Call: _e.mock.On("CompleteRecommendation", ctx, userID, id)}
}

func (_c *Service_CompleteRecommendation_Call) Run(run func(ctx context.Context, userID string, id string)) *Service_CompleteRecommendation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Service_CompleteRecommendation_Call) Return(_a0 error) *Service_CompleteRecommendation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_CompleteRecommendation_Call) RunAndReturn(run func(context.Context, string, string) error) *Service_CompleteRecommendation_Call {
	_c.Call.Return(run)
	return _c
}

// DismissRecommendation provides a mock function with given fields: ctx, userID, id
func (_m *Service) DismissRecommendation(ctx context.Context, userID string, id string) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DismissRecommendation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_DismissRecommendation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DismissRecommendation'
type Service_DismissRecommendation_Call struct {
	*mock.Call
}

// DismissRecommendation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *Service_Expecter) DismissRecommendation(ctx interface{}, userID interface{}, id interface{}) *Service_DismissRecommendation_Call {
	return &Service_DismissRecommendation_Call{Call: _e.mock.On("DismissRecommendation", ctx, userID, id)}
}

func (_c *Service_DismissRecommendation_Call) Run(run func(ctx context.Context, userID string, id string)) *Service_DismissRecommendation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Service_DismissRecommendation_Call) Return(_a0 error) *Service_DismissRecommendation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_DismissRecommendation_Call) RunAndReturn(run func(context.Context, string, string) error) *Service_DismissRecommendation_Call {
	_c.Call.Return(run)
	return _c
}

// GetDashboard provides a mock function with given fields: ctx, userID
func (_m *Service) GetDashboard(ctx context.Context, userID string) (*model.Dashboard, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDashboard")
	}

	var r0 *model.Dashboard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Dashboard, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Dashboard); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Dashboard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetDashboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDashboard'
type Service_GetDashboard_Call struct {
	*mock.Call
}

// GetDashboard is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Service_Expecter) GetDashboard(ctx interface{}, userID interface{}) *Service_GetDashboard_Call {
	return &Service_GetDashboard_Call{Call: _e.mock.On("GetDashboard", ctx, userID)}
}

func (_c *Service_GetDashboard_Call) Run(run func(ctx context.Context, userID string)) *Service_GetDashboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Service_GetDashboard_Call) Return(_a0 *model.Dashboard, _a1 error) *Service_GetDashboard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetDashboard_Call) RunAndReturn(run func(context.Context, string) (*model.Dashboard, error)) *Service_GetDashboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetMockHubContext provides a mock function with given fields: ctx, userID
func (_m *Service) GetMockHubContext(ctx context.Context, userID string) (*model.MockHubContext, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMockHubContext")
	}

	var r0 *model.MockHubContext
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.MockHubContext, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.MockHubContext); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MockHubContext)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetMockHubContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMockHubContext'
type Service_GetMockHubContext_Call struct {
	*mock.Call
}

// GetMockHubContext is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Service_Expecter) GetMockHubContext(ctx interface{}, userID interface{}) *Service_GetMockHubContext_Call {
	return &Service_GetMockHubContext_Call{Call: _e.mock.On("GetMockHubContext", ctx, userID)}
}

func (_c *Service_GetMockHubContext_Call) Run(run func(ctx context.Context, userID string)) *Service_GetMockHubContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Service_GetMockHubContext_Call) Return(_a0 *model.MockHubContext, _a1 error) *Service_GetMockHubContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetMockHubContext_Call) RunAndReturn(run func(context.Context, string) (*model.MockHubContext, error)) *Service_GetMockHubContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskPickerHints provides a mock function with given fields: ctx, userID, taskType
func (_m *Service) GetTaskPickerHints(ctx context.Context, userID string, taskType string) (*model.TaskPickerHints, error) {
	ret := _m.Called(ctx, userID, taskType)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskPickerHints")
	}

	var r0 *model.TaskPickerHints
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.TaskPickerHints, error)); ok {
		return rf(ctx, userID, taskType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.TaskPickerHints); ok {
		r0 = rf(ctx, userID, taskType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TaskPickerHints)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, taskType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetTaskPickerHints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskPickerHints'
type Service_GetTaskPickerHints_Call struct {
	*mock.Call
}

// GetTaskPickerHints is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - taskType string
func (_e *Service_Expecter) GetTaskPickerHints(ctx interface{}, userID interface{}, taskType interface{}) *Service_GetTaskPickerHints_Call {
	return &Service_GetTaskPickerHints_Call{Call: _e.mock.On("GetTaskPickerHints", ctx, userID, taskType)}
}

func (_c *Service_GetTaskPickerHints_Call) Run(run func(ctx context.Context, userID string, taskType string)) *Service_GetTaskPickerHints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Service_GetTaskPickerHints_Call) Return(_a0 *model.TaskPickerHints, _a1 error) *Service_GetTaskPickerHints_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetTaskPickerHints_Call) RunAndReturn(run func(context.Context, string, string) (*model.TaskPickerHints, error)) *Service_GetTaskPickerHints_Call {
	_c.Call.Return(run)
	return _c
}

// HandleAttemptEvaluated provides a mock function with given fields: ctx, eventID, event
func (_m *Service) HandleAttemptEvaluated(ctx context.Context, eventID string, event model.AttemptEvaluatedEvent) error {
	ret := _m.Called(ctx, eventID, event)

	if len(ret) == 0 {
		panic("no return value specified for HandleAttemptEvaluated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.AttemptEvaluatedEvent) error); ok {
		r0 = rf(ctx, eventID, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_HandleAttemptEvaluated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleAttemptEvaluated'
type Service_HandleAttemptEvaluated_Call struct {
	*mock.Call
}

// HandleAttemptEvaluated is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - event model.AttemptEvaluatedEvent
func (_e *Service_Expecter) HandleAttemptEvaluated(ctx interface{}, eventID interface{}, event interface{}) *Service_HandleAttemptEvaluated_Call {
	return &Service_HandleAttemptEvaluated_Call{Call: _e.mock.On("HandleAttemptEvaluated", ctx, eventID, event)}
}

func (_c *Service_HandleAttemptEvaluated_Call) Run(run func(ctx context.Context, eventID string, event model.AttemptEvaluatedEvent)) *Service_HandleAttemptEvaluated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.AttemptEvaluatedEvent))
	})
	return _c
}

func (_c *Service_HandleAttemptEvaluated_Call) Return(_a0 error) *Service_HandleAttemptEvaluated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_HandleAttemptEvaluated_Call) RunAndReturn(run func(context.Context, string, model.AttemptEvaluatedEvent) error) *Service_HandleAttemptEvaluated_Call {
	_c.Call.Return(run)
	return _c
}

// HandleRetryItemCreated provides a mock function with given fields: ctx, eventID, event
func (_m *Service) HandleRetryItemCreated(ctx context.Context, eventID string, event model.RetryItemCreatedEvent) error {
	ret := _m.Called(ctx, eventID, event)

	if len(ret) == 0 {
		panic("no return value specified for HandleRetryItemCreated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.RetryItemCreatedEvent) error); ok {
		r0 = rf(ctx, eventID, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_HandleRetryItemCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleRetryItemCreated'
type Service_HandleRetryItemCreated_Call struct {
	*mock.Call
}

// HandleRetryItemCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - event model.RetryItemCreatedEvent
func (_e *Service_Expecter) HandleRetryItemCreated(ctx interface{}, eventID interface{}, event interface{}) *Service_HandleRetryItemCreated_Call {
	return &Service_HandleRetryItemCreated_Call{Call: _e.mock.On("HandleRetryItemCreated", ctx, eventID, event)}
}

func (_c *Service_HandleRetryItemCreated_Call) Run(run func(ctx context.Context, eventID string, event model.RetryItemCreatedEvent)) *Service_HandleRetryItemCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.RetryItemCreatedEvent))
	})
	return _c
}

func (_c *Service_HandleRetryItemCreated_Call) Return(_a0 error) *Service_HandleRetryItemCreated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_HandleRetryItemCreated_Call) RunAndReturn(run func(context.Context, string, model.RetryItemCreatedEvent) error) *Service_HandleRetryItemCreated_Call {
	_c.Call.Return(run)
	return _c
}

// HandleSessionCompleted provides a mock function with given fields: ctx, eventID, event
func (_m *Service) HandleSessionCompleted(ctx context.Context, eventID string, event model.SessionCompletedEvent) error {
	ret := _m.Called(ctx, eventID, event)

	if len(ret) == 0 {
		panic("no return value specified for HandleSessionCompleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.SessionCompletedEvent) error); ok {
		r0 = rf(ctx, eventID, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_HandleSessionCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleSessionCompleted'
type Service_HandleSessionCompleted_Call struct {
	*mock.Call
}

// HandleSessionCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - event model.SessionCompletedEvent
func (_e *Service_Expecter) HandleSessionCompleted(ctx interface{}, eventID interface{}, event interface{}) *Service_HandleSessionCompleted_Call {
	return &Service_HandleSessionCompleted_Call{Call: _e.mock.On("HandleSessionCompleted", ctx, eventID, event)}
}

func (_c *Service_HandleSessionCompleted_Call) Run(run func(ctx context.Context, eventID string, event model.SessionCompletedEvent)) *Service_HandleSessionCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.SessionCompletedEvent))
	})
	return _c
}

func (_c *Service_HandleSessionCompleted_Call) Return(_a0 error) *Service_HandleSessionCompleted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_HandleSessionCompleted_Call) RunAndReturn(run func(context.Context, string, model.SessionCompletedEvent) error) *Service_HandleSessionCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// HandleTaskSkipped provides a mock function with given fields: ctx, eventID, event
func (_m *Service) HandleTaskSkipped(ctx context.Context, eventID string, event model.TaskSkippedEvent) error {
	ret := _m.Called(ctx, eventID, event)

	if len(ret) == 0 {
		panic("no return value specified for HandleTaskSkipped")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.TaskSkippedEvent) error); ok {
		r0 = rf(ctx, eventID, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_HandleTaskSkipped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleTaskSkipped'
type Service_HandleTaskSkipped_Call struct {
	*mock.Call
}

// HandleTaskSkipped is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - event model.TaskSkippedEvent
func (_e *Service_Expecter) HandleTaskSkipped(ctx interface{}, eventID interface{}, event interface{}) *Service_HandleTaskSkipped_Call {
	return &Service_HandleTaskSkipped_Call{Call: _e.mock.On("HandleTaskSkipped", ctx, eventID, event)}
}

func (_c *Service_HandleTaskSkipped_Call) Run(run func(ctx context.Context, eventID string, event model.TaskSkippedEvent)) *Service_HandleTaskSkipped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.TaskSkippedEvent))
	})
	return _c
}

func (_c *Service_HandleTaskSkipped_Call) Return(_a0 error) *Service_HandleTaskSkipped_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_HandleTaskSkipped_Call) RunAndReturn(run func(context.Context, string, model.TaskSkippedEvent) error) *Service_HandleTaskSkipped_Call {
	_c.Call.Return(run)
	return _c
}

// HandleTrackerTaskCompleted provides a mock function with given fields: ctx, eventID, payload
func (_m *Service) HandleTrackerTaskCompleted(ctx context.Context, eventID string, payload map[string]interface{}) error {
	ret := _m.Called(ctx, eventID, payload)

	if len(ret) == 0 {
		panic("no return value specified for HandleTrackerTaskCompleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, eventID, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_HandleTrackerTaskCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleTrackerTaskCompleted'
type Service_HandleTrackerTaskCompleted_Call struct {
	*mock.Call
}

// HandleTrackerTaskCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - payload map[string]interface{}
func (_e *Service_Expecter) HandleTrackerTaskCompleted(ctx interface{}, eventID interface{}, payload interface{}) *Service_HandleTrackerTaskCompleted_Call {
	return &Service_HandleTrackerTaskCompleted_Call{Call: _e.mock.On("HandleTrackerTaskCompleted", ctx, eventID, payload)}
}

func (_c *Service_HandleTrackerTaskCompleted_Call) Run(run func(ctx context.Context, eventID string, payload map[string]interface{})) *Service_HandleTrackerTaskCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *Service_HandleTrackerTaskCompleted_Call) Return(_a0 error) *Service_HandleTrackerTaskCompleted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_HandleTrackerTaskCompleted_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}) error) *Service_HandleTrackerTaskCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// HandleTrackerTaskCreated provides a mock function with given fields: ctx, eventID, payload
func (_m *Service) HandleTrackerTaskCreated(ctx context.Context, eventID string, payload map[string]interface{}) error {
	ret := _m.Called(ctx, eventID, payload)

	if len(ret) == 0 {
		panic("no return value specified for HandleTrackerTaskCreated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, eventID, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_HandleTrackerTaskCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleTrackerTaskCreated'
type Service_HandleTrackerTaskCreated_Call struct {
	*mock.Call
}

// HandleTrackerTaskCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - payload map[string]interface{}
func (_e *Service_Expecter) HandleTrackerTaskCreated(ctx interface{}, eventID interface{}, payload interface{}) *Service_HandleTrackerTaskCreated_Call {
	return &Service_HandleTrackerTaskCreated_Call{Call: _e.mock.On("HandleTrackerTaskCreated", ctx, eventID, payload)}
}

func (_c *Service_HandleTrackerTaskCreated_Call) Run(run func(ctx context.Context, eventID string, payload map[string]interface{})) *Service_HandleTrackerTaskCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *Service_HandleTrackerTaskCreated_Call) Return(_a0 error) *Service_HandleTrackerTaskCreated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_HandleTrackerTaskCreated_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}) error) *Service_HandleTrackerTaskCreated_Call {
	_c.Call.Return(run)
	return _c
}

// MarkArticleRead provides a mock function with given fields: ctx, userID, slug
func (_m *Service) MarkArticleRead(ctx context.Context, userID string, slug string) (*model.ArticleRead, error) {
	ret := _m.Called(ctx, userID, slug)

	if len(ret) == 0 {
		panic("no return value specified for MarkArticleRead")
	}

	var r0 *model.ArticleRead
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.ArticleRead, error)); ok {
		return rf(ctx, userID, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.ArticleRead); ok {
		r0 = rf(ctx, userID, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ArticleRead)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_MarkArticleRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkArticleRead'
type Service_MarkArticleRead_Call struct {
	*mock.Call
}

// MarkArticleRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - slug string
func (_e *Service_Expecter) MarkArticleRead(ctx interface{}, userID interface{}, slug interface{}) *Service_MarkArticleRead_Call {
	return &Service_MarkArticleRead_Call{Call: _e.mock.On("MarkArticleRead", ctx, userID, slug)}
}

func (_c *Service_MarkArticleRead_Call) Run(run func(ctx context.Context, userID string, slug string)) *Service_MarkArticleRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Service_MarkArticleRead_Call) Return(_a0 *model.ArticleRead, _a1 error) *Service_MarkArticleRead_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_MarkArticleRead_Call) RunAndReturn(run func(context.Context, string, string) (*model.ArticleRead, error)) *Service_MarkArticleRead_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
