// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	llm "github.com/sedorofeevd/project-druzya/services/ai/internal/adapter/llm"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// Evaluate provides a mock function with given fields: ctx, req
func (_m *Client) Evaluate(ctx context.Context, req llm.EvaluateRequest) (llm.EvaluateResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Evaluate")
	}

	var r0 llm.EvaluateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, llm.EvaluateRequest) (llm.EvaluateResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, llm.EvaluateRequest) llm.EvaluateResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(llm.EvaluateResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, llm.EvaluateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_Evaluate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Evaluate'
type Client_Evaluate_Call struct {
	*mock.Call
}

// Evaluate is a helper method to define mock.On call
//   - ctx context.Context
//   - req llm.EvaluateRequest
func (_e *Client_Expecter) Evaluate(ctx interface{}, req interface{}) *Client_Evaluate_Call {
	return &Client_Evaluate_Call{Call: _e.mock.On("Evaluate", ctx, req)}
}

func (_c *Client_Evaluate_Call) Run(run func(ctx context.Context, req llm.EvaluateRequest)) *Client_Evaluate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(llm.EvaluateRequest))
	})
	return _c
}

func (_c *Client_Evaluate_Call) Return(_a0 llm.EvaluateResponse, _a1 error) *Client_Evaluate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_Evaluate_Call) RunAndReturn(run func(context.Context, llm.EvaluateRequest) (llm.EvaluateResponse, error)) *Client_Evaluate_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
