export const enumsRu = {
  sessionMode: {
    company_interview: 'Mock под компанию',
    algorithms_training: 'Алгоритмы',
    live_coding_training: 'Live coding',
    system_design_training: 'System design',
    behavioral_training: 'Behavioral',
    sql_training: 'SQL',
    retry_mistakes: 'Повтор ошибок',
    unspecified: 'Сессия',
  },
  sessionStatus: {
    active: 'Активна',
    completed: 'Завершена',
    cancelled: 'Отменена',
    expired: 'Истекла',
    unspecified: '—',
  },
  sectionStatus: {
    pending: 'Ожидает',
    active: 'Текущая',
    completed: 'Готово',
    unspecified: '—',
  },
  attemptStatus: {
    submitted: 'Отправлено',
    evaluating: 'Оценивается',
    evaluated: 'Оценено',
    failed: 'Ошибка',
    cancelled: 'Отменено',
    unspecified: '—',
  },
  taskType: {
    algorithm: 'Алгоритмы',
    live_coding: 'Live coding',
    system_design: 'System design',
    behavioral: 'Behavioral',
    sql: 'SQL',
    unspecified: 'Задача',
  },
  skillDomain: {
    algorithm: 'Алгоритмы',
    algorithms: 'Алгоритмы',
    behavioral: 'Behavioral',
    system: 'System design',
    sysdesign: 'System design',
    system_design: 'System design',
    coding: 'Live coding',
    live_coding: 'Live coding',
    sql: 'SQL',
  },
  skillCriterion: {
    overall: 'Итог',
    correctness: 'Корректность',
    communication: 'Коммуникация',
    star_structure: 'STAR-структура',
    complexity_analysis: 'Сложность',
    code_quality: 'Качество кода',
    scalability: 'Масштабирование',
    tradeoffs: 'Компромиссы',
    arrays: 'Массивы',
    strings: 'Строки',
    trees: 'Деревья',
    graphs: 'Графы',
    dynamic_programming: 'Dynamic programming',
    recursion: 'Рекурсия',
    sorting: 'Сортировка',
    searching: 'Поиск',
    hash_tables: 'Хеш-таблицы',
    heaps: 'Кучи',
    greedy: 'Жадные алгоритмы',
    design: 'Проектирование',
  },
  skillKeys: {
    behavioral_overall: 'Behavioral — итог',
    algorithm_overall: 'Алгоритмы — итог',
    algorithm_correctness: 'Алгоритмы — корректность',
    algorithm_arrays: 'Алгоритмы — массивы',
    live_coding_overall: 'Live coding — итог',
    system_design_overall: 'System design — итог',
    sql_overall: 'SQL — итог',
  },
  difficulty: {
    easy: 'Лёгкая',
    medium: 'Средняя',
    hard: 'Сложная',
    unspecified: '—',
  },
  sectionType: {
    algorithm: 'Алгоритмы',
    algorithms: 'Алгоритмы',
    live_coding: 'Live coding',
    system_design: 'System design',
    behavioral: 'Behavioral',
    sql: 'SQL',
  },
} as const
