// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	content "github.com/sedorofeevd/project-druzya/services/recommendation/internal/adapter/content"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// GetTask provides a mock function with given fields: ctx, taskID
func (_m *Client) GetTask(ctx context.Context, taskID string) (*content.Task, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 *content.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*content.Task, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *content.Task); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type Client_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *Client_Expecter) GetTask(ctx interface{}, taskID interface{}) *Client_GetTask_Call {
	return &Client_GetTask_Call{Call: _e.mock.On("GetTask", ctx, taskID)}
}

func (_c *Client_GetTask_Call) Run(run func(ctx context.Context, taskID string)) *Client_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_GetTask_Call) Return(_a0 *content.Task, _a1 error) *Client_GetTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetTask_Call) RunAndReturn(run func(context.Context, string) (*content.Task, error)) *Client_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// ListArticlesBySkillKeys provides a mock function with given fields: ctx, skillKeys
func (_m *Client) ListArticlesBySkillKeys(ctx context.Context, skillKeys []string) ([]content.Article, error) {
	ret := _m.Called(ctx, skillKeys)

	if len(ret) == 0 {
		panic("no return value specified for ListArticlesBySkillKeys")
	}

	var r0 []content.Article
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]content.Article, error)); ok {
		return rf(ctx, skillKeys)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []content.Article); ok {
		r0 = rf(ctx, skillKeys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]content.Article)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, skillKeys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ListArticlesBySkillKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListArticlesBySkillKeys'
type Client_ListArticlesBySkillKeys_Call struct {
	*mock.Call
}

// ListArticlesBySkillKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - skillKeys []string
func (_e *Client_Expecter) ListArticlesBySkillKeys(ctx interface{}, skillKeys interface{}) *Client_ListArticlesBySkillKeys_Call {
	return &Client_ListArticlesBySkillKeys_Call{Call: _e.mock.On("ListArticlesBySkillKeys", ctx, skillKeys)}
}

func (_c *Client_ListArticlesBySkillKeys_Call) Run(run func(ctx context.Context, skillKeys []string)) *Client_ListArticlesBySkillKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *Client_ListArticlesBySkillKeys_Call) Return(_a0 []content.Article, _a1 error) *Client_ListArticlesBySkillKeys_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_ListArticlesBySkillKeys_Call) RunAndReturn(run func(context.Context, []string) ([]content.Article, error)) *Client_ListArticlesBySkillKeys_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
