// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/sedorofeevd/project-druzya/services/interview/internal/interview/model"
	repository "github.com/sedorofeevd/project-druzya/services/interview/internal/interview/repository"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// AckOutboxEvents provides a mock function with given fields: ctx, ids
func (_m *Repository) AckOutboxEvents(ctx context.Context, ids []string) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for AckOutboxEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_AckOutboxEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AckOutboxEvents'
type Repository_AckOutboxEvents_Call struct {
	*mock.Call
}

// AckOutboxEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *Repository_Expecter) AckOutboxEvents(ctx interface{}, ids interface{}) *Repository_AckOutboxEvents_Call {
	return &Repository_AckOutboxEvents_Call{Call: _e.mock.On("AckOutboxEvents", ctx, ids)}
}

func (_c *Repository_AckOutboxEvents_Call) Run(run func(ctx context.Context, ids []string)) *Repository_AckOutboxEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *Repository_AckOutboxEvents_Call) Return(_a0 error) *Repository_AckOutboxEvents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_AckOutboxEvents_Call) RunAndReturn(run func(context.Context, []string) error) *Repository_AckOutboxEvents_Call {
	_c.Call.Return(run)
	return _c
}

// ClaimOutboxEvents provides a mock function with given fields: ctx, eventName, limit
func (_m *Repository) ClaimOutboxEvents(ctx context.Context, eventName string, limit int) ([]model.OutboxMessage, error) {
	ret := _m.Called(ctx, eventName, limit)

	if len(ret) == 0 {
		panic("no return value specified for ClaimOutboxEvents")
	}

	var r0 []model.OutboxMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]model.OutboxMessage, error)); ok {
		return rf(ctx, eventName, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []model.OutboxMessage); ok {
		r0 = rf(ctx, eventName, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.OutboxMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, eventName, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ClaimOutboxEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimOutboxEvents'
type Repository_ClaimOutboxEvents_Call struct {
	*mock.Call
}

// ClaimOutboxEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - eventName string
//   - limit int
func (_e *Repository_Expecter) ClaimOutboxEvents(ctx interface{}, eventName interface{}, limit interface{}) *Repository_ClaimOutboxEvents_Call {
	return &Repository_ClaimOutboxEvents_Call{Call: _e.mock.On("ClaimOutboxEvents", ctx, eventName, limit)}
}

func (_c *Repository_ClaimOutboxEvents_Call) Run(run func(ctx context.Context, eventName string, limit int)) *Repository_ClaimOutboxEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *Repository_ClaimOutboxEvents_Call) Return(_a0 []model.OutboxMessage, _a1 error) *Repository_ClaimOutboxEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ClaimOutboxEvents_Call) RunAndReturn(run func(context.Context, string, int) ([]model.OutboxMessage, error)) *Repository_ClaimOutboxEvents_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAttempt provides a mock function with given fields: ctx, attempt
func (_m *Repository) CreateAttempt(ctx context.Context, attempt *model.Attempt) error {
	ret := _m.Called(ctx, attempt)

	if len(ret) == 0 {
		panic("no return value specified for CreateAttempt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Attempt) error); ok {
		r0 = rf(ctx, attempt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_CreateAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAttempt'
type Repository_CreateAttempt_Call struct {
	*mock.Call
}

// CreateAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - attempt *model.Attempt
func (_e *Repository_Expecter) CreateAttempt(ctx interface{}, attempt interface{}) *Repository_CreateAttempt_Call {
	return &Repository_CreateAttempt_Call{Call: _e.mock.On("CreateAttempt", ctx, attempt)}
}

func (_c *Repository_CreateAttempt_Call) Run(run func(ctx context.Context, attempt *model.Attempt)) *Repository_CreateAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Attempt))
	})
	return _c
}

func (_c *Repository_CreateAttempt_Call) Return(_a0 error) *Repository_CreateAttempt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_CreateAttempt_Call) RunAndReturn(run func(context.Context, *model.Attempt) error) *Repository_CreateAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEvaluationSummary provides a mock function with given fields: ctx, summary
func (_m *Repository) CreateEvaluationSummary(ctx context.Context, summary *model.EvaluationSummary) error {
	ret := _m.Called(ctx, summary)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvaluationSummary")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.EvaluationSummary) error); ok {
		r0 = rf(ctx, summary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_CreateEvaluationSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEvaluationSummary'
type Repository_CreateEvaluationSummary_Call struct {
	*mock.Call
}

// CreateEvaluationSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - summary *model.EvaluationSummary
func (_e *Repository_Expecter) CreateEvaluationSummary(ctx interface{}, summary interface{}) *Repository_CreateEvaluationSummary_Call {
	return &Repository_CreateEvaluationSummary_Call{Call: _e.mock.On("CreateEvaluationSummary", ctx, summary)}
}

func (_c *Repository_CreateEvaluationSummary_Call) Run(run func(ctx context.Context, summary *model.EvaluationSummary)) *Repository_CreateEvaluationSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.EvaluationSummary))
	})
	return _c
}

func (_c *Repository_CreateEvaluationSummary_Call) Return(_a0 error) *Repository_CreateEvaluationSummary_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_CreateEvaluationSummary_Call) RunAndReturn(run func(context.Context, *model.EvaluationSummary) error) *Repository_CreateEvaluationSummary_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRetryItemIfAbsent provides a mock function with given fields: ctx, item
func (_m *Repository) CreateRetryItemIfAbsent(ctx context.Context, item *model.RetryItem) (bool, error) {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for CreateRetryItemIfAbsent")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.RetryItem) (bool, error)); ok {
		return rf(ctx, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.RetryItem) bool); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.RetryItem) error); ok {
		r1 = rf(ctx, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CreateRetryItemIfAbsent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRetryItemIfAbsent'
type Repository_CreateRetryItemIfAbsent_Call struct {
	*mock.Call
}

// CreateRetryItemIfAbsent is a helper method to define mock.On call
//   - ctx context.Context
//   - item *model.RetryItem
func (_e *Repository_Expecter) CreateRetryItemIfAbsent(ctx interface{}, item interface{}) *Repository_CreateRetryItemIfAbsent_Call {
	return &Repository_CreateRetryItemIfAbsent_Call{Call: _e.mock.On("CreateRetryItemIfAbsent", ctx, item)}
}

func (_c *Repository_CreateRetryItemIfAbsent_Call) Run(run func(ctx context.Context, item *model.RetryItem)) *Repository_CreateRetryItemIfAbsent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.RetryItem))
	})
	return _c
}

func (_c *Repository_CreateRetryItemIfAbsent_Call) Return(_a0 bool, _a1 error) *Repository_CreateRetryItemIfAbsent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CreateRetryItemIfAbsent_Call) RunAndReturn(run func(context.Context, *model.RetryItem) (bool, error)) *Repository_CreateRetryItemIfAbsent_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRetrySession provides a mock function with given fields: ctx, bundle, retryItemIDs, at
func (_m *Repository) CreateRetrySession(ctx context.Context, bundle repository.SessionBundle, retryItemIDs []string, at time.Time) error {
	ret := _m.Called(ctx, bundle, retryItemIDs, at)

	if len(ret) == 0 {
		panic("no return value specified for CreateRetrySession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.SessionBundle, []string, time.Time) error); ok {
		r0 = rf(ctx, bundle, retryItemIDs, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_CreateRetrySession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRetrySession'
type Repository_CreateRetrySession_Call struct {
	*mock.Call
}

// CreateRetrySession is a helper method to define mock.On call
//   - ctx context.Context
//   - bundle repository.SessionBundle
//   - retryItemIDs []string
//   - at time.Time
func (_e *Repository_Expecter) CreateRetrySession(ctx interface{}, bundle interface{}, retryItemIDs interface{}, at interface{}) *Repository_CreateRetrySession_Call {
	return &Repository_CreateRetrySession_Call{Call: _e.mock.On("CreateRetrySession", ctx, bundle, retryItemIDs, at)}
}

func (_c *Repository_CreateRetrySession_Call) Run(run func(ctx context.Context, bundle repository.SessionBundle, retryItemIDs []string, at time.Time)) *Repository_CreateRetrySession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.SessionBundle), args[2].([]string), args[3].(time.Time))
	})
	return _c
}

func (_c *Repository_CreateRetrySession_Call) Return(_a0 error) *Repository_CreateRetrySession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_CreateRetrySession_Call) RunAndReturn(run func(context.Context, repository.SessionBundle, []string, time.Time) error) *Repository_CreateRetrySession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSessionBundle provides a mock function with given fields: ctx, bundle
func (_m *Repository) CreateSessionBundle(ctx context.Context, bundle repository.SessionBundle) error {
	ret := _m.Called(ctx, bundle)

	if len(ret) == 0 {
		panic("no return value specified for CreateSessionBundle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.SessionBundle) error); ok {
		r0 = rf(ctx, bundle)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_CreateSessionBundle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSessionBundle'
type Repository_CreateSessionBundle_Call struct {
	*mock.Call
}

// CreateSessionBundle is a helper method to define mock.On call
//   - ctx context.Context
//   - bundle repository.SessionBundle
func (_e *Repository_Expecter) CreateSessionBundle(ctx interface{}, bundle interface{}) *Repository_CreateSessionBundle_Call {
	return &Repository_CreateSessionBundle_Call{Call: _e.mock.On("CreateSessionBundle", ctx, bundle)}
}

func (_c *Repository_CreateSessionBundle_Call) Run(run func(ctx context.Context, bundle repository.SessionBundle)) *Repository_CreateSessionBundle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.SessionBundle))
	})
	return _c
}

func (_c *Repository_CreateSessionBundle_Call) Return(_a0 error) *Repository_CreateSessionBundle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_CreateSessionBundle_Call) RunAndReturn(run func(context.Context, repository.SessionBundle) error) *Repository_CreateSessionBundle_Call {
	_c.Call.Return(run)
	return _c
}

// ExpireStaleActiveSessions provides a mock function with given fields: ctx, idleBefore, maxAgeBefore
func (_m *Repository) ExpireStaleActiveSessions(ctx context.Context, idleBefore time.Time, maxAgeBefore time.Time) (int64, error) {
	ret := _m.Called(ctx, idleBefore, maxAgeBefore)

	if len(ret) == 0 {
		panic("no return value specified for ExpireStaleActiveSessions")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) (int64, error)); ok {
		return rf(ctx, idleBefore, maxAgeBefore)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) int64); ok {
		r0 = rf(ctx, idleBefore, maxAgeBefore)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, idleBefore, maxAgeBefore)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ExpireStaleActiveSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpireStaleActiveSessions'
type Repository_ExpireStaleActiveSessions_Call struct {
	*mock.Call
}

// ExpireStaleActiveSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - idleBefore time.Time
//   - maxAgeBefore time.Time
func (_e *Repository_Expecter) ExpireStaleActiveSessions(ctx interface{}, idleBefore interface{}, maxAgeBefore interface{}) *Repository_ExpireStaleActiveSessions_Call {
	return &Repository_ExpireStaleActiveSessions_Call{Call: _e.mock.On("ExpireStaleActiveSessions", ctx, idleBefore, maxAgeBefore)}
}

func (_c *Repository_ExpireStaleActiveSessions_Call) Run(run func(ctx context.Context, idleBefore time.Time, maxAgeBefore time.Time)) *Repository_ExpireStaleActiveSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *Repository_ExpireStaleActiveSessions_Call) Return(_a0 int64, _a1 error) *Repository_ExpireStaleActiveSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ExpireStaleActiveSessions_Call) RunAndReturn(run func(context.Context, time.Time, time.Time) (int64, error)) *Repository_ExpireStaleActiveSessions_Call {
	_c.Call.Return(run)
	return _c
}

// FailOutboxEvent provides a mock function with given fields: ctx, id, errMsg, retryDelay
func (_m *Repository) FailOutboxEvent(ctx context.Context, id string, errMsg string, retryDelay time.Duration) error {
	ret := _m.Called(ctx, id, errMsg, retryDelay)

	if len(ret) == 0 {
		panic("no return value specified for FailOutboxEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, id, errMsg, retryDelay)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_FailOutboxEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailOutboxEvent'
type Repository_FailOutboxEvent_Call struct {
	*mock.Call
}

// FailOutboxEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - errMsg string
//   - retryDelay time.Duration
func (_e *Repository_Expecter) FailOutboxEvent(ctx interface{}, id interface{}, errMsg interface{}, retryDelay interface{}) *Repository_FailOutboxEvent_Call {
	return &Repository_FailOutboxEvent_Call{Call: _e.mock.On("FailOutboxEvent", ctx, id, errMsg, retryDelay)}
}

func (_c *Repository_FailOutboxEvent_Call) Run(run func(ctx context.Context, id string, errMsg string, retryDelay time.Duration)) *Repository_FailOutboxEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *Repository_FailOutboxEvent_Call) Return(_a0 error) *Repository_FailOutboxEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_FailOutboxEvent_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) error) *Repository_FailOutboxEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveSessionForUser provides a mock function with given fields: ctx, userID
func (_m *Repository) GetActiveSessionForUser(ctx context.Context, userID string) (*model.Session, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveSessionForUser")
	}

	var r0 *model.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Session, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Session); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetActiveSessionForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveSessionForUser'
type Repository_GetActiveSessionForUser_Call struct {
	*mock.Call
}

// GetActiveSessionForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Repository_Expecter) GetActiveSessionForUser(ctx interface{}, userID interface{}) *Repository_GetActiveSessionForUser_Call {
	return &Repository_GetActiveSessionForUser_Call{Call: _e.mock.On("GetActiveSessionForUser", ctx, userID)}
}

func (_c *Repository_GetActiveSessionForUser_Call) Run(run func(ctx context.Context, userID string)) *Repository_GetActiveSessionForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_GetActiveSessionForUser_Call) Return(_a0 *model.Session, _a1 error) *Repository_GetActiveSessionForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetActiveSessionForUser_Call) RunAndReturn(run func(context.Context, string) (*model.Session, error)) *Repository_GetActiveSessionForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttemptByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetAttemptByID(ctx context.Context, id string) (*model.Attempt, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAttemptByID")
	}

	var r0 *model.Attempt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Attempt, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Attempt); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Attempt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetAttemptByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttemptByID'
type Repository_GetAttemptByID_Call struct {
	*mock.Call
}

// GetAttemptByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Repository_Expecter) GetAttemptByID(ctx interface{}, id interface{}) *Repository_GetAttemptByID_Call {
	return &Repository_GetAttemptByID_Call{Call: _e.mock.On("GetAttemptByID", ctx, id)}
}

func (_c *Repository_GetAttemptByID_Call) Run(run func(ctx context.Context, id string)) *Repository_GetAttemptByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_GetAttemptByID_Call) Return(_a0 *model.Attempt, _a1 error) *Repository_GetAttemptByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetAttemptByID_Call) RunAndReturn(run func(context.Context, string) (*model.Attempt, error)) *Repository_GetAttemptByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttemptForUser provides a mock function with given fields: ctx, userID, attemptID
func (_m *Repository) GetAttemptForUser(ctx context.Context, userID string, attemptID string) (*model.Attempt, error) {
	ret := _m.Called(ctx, userID, attemptID)

	if len(ret) == 0 {
		panic("no return value specified for GetAttemptForUser")
	}

	var r0 *model.Attempt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Attempt, error)); ok {
		return rf(ctx, userID, attemptID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Attempt); ok {
		r0 = rf(ctx, userID, attemptID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Attempt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, attemptID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetAttemptForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttemptForUser'
type Repository_GetAttemptForUser_Call struct {
	*mock.Call
}

// GetAttemptForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - attemptID string
func (_e *Repository_Expecter) GetAttemptForUser(ctx interface{}, userID interface{}, attemptID interface{}) *Repository_GetAttemptForUser_Call {
	return &Repository_GetAttemptForUser_Call{Call: _e.mock.On("GetAttemptForUser", ctx, userID, attemptID)}
}

func (_c *Repository_GetAttemptForUser_Call) Run(run func(ctx context.Context, userID string, attemptID string)) *Repository_GetAttemptForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_GetAttemptForUser_Call) Return(_a0 *model.Attempt, _a1 error) *Repository_GetAttemptForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetAttemptForUser_Call) RunAndReturn(run func(context.Context, string, string) (*model.Attempt, error)) *Repository_GetAttemptForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvaluationSummaryByAttemptID provides a mock function with given fields: ctx, attemptID
func (_m *Repository) GetEvaluationSummaryByAttemptID(ctx context.Context, attemptID string) (*model.EvaluationSummary, error) {
	ret := _m.Called(ctx, attemptID)

	if len(ret) == 0 {
		panic("no return value specified for GetEvaluationSummaryByAttemptID")
	}

	var r0 *model.EvaluationSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.EvaluationSummary, error)); ok {
		return rf(ctx, attemptID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.EvaluationSummary); ok {
		r0 = rf(ctx, attemptID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.EvaluationSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, attemptID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetEvaluationSummaryByAttemptID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvaluationSummaryByAttemptID'
type Repository_GetEvaluationSummaryByAttemptID_Call struct {
	*mock.Call
}

// GetEvaluationSummaryByAttemptID is a helper method to define mock.On call
//   - ctx context.Context
//   - attemptID string
func (_e *Repository_Expecter) GetEvaluationSummaryByAttemptID(ctx interface{}, attemptID interface{}) *Repository_GetEvaluationSummaryByAttemptID_Call {
	return &Repository_GetEvaluationSummaryByAttemptID_Call{Call: _e.mock.On("GetEvaluationSummaryByAttemptID", ctx, attemptID)}
}

func (_c *Repository_GetEvaluationSummaryByAttemptID_Call) Run(run func(ctx context.Context, attemptID string)) *Repository_GetEvaluationSummaryByAttemptID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_GetEvaluationSummaryByAttemptID_Call) Return(_a0 *model.EvaluationSummary, _a1 error) *Repository_GetEvaluationSummaryByAttemptID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetEvaluationSummaryByAttemptID_Call) RunAndReturn(run func(context.Context, string) (*model.EvaluationSummary, error)) *Repository_GetEvaluationSummaryByAttemptID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRetryItemForUser provides a mock function with given fields: ctx, userID, retryItemID
func (_m *Repository) GetRetryItemForUser(ctx context.Context, userID string, retryItemID string) (*model.RetryItem, error) {
	ret := _m.Called(ctx, userID, retryItemID)

	if len(ret) == 0 {
		panic("no return value specified for GetRetryItemForUser")
	}

	var r0 *model.RetryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.RetryItem, error)); ok {
		return rf(ctx, userID, retryItemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.RetryItem); ok {
		r0 = rf(ctx, userID, retryItemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RetryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, retryItemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetRetryItemForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRetryItemForUser'
type Repository_GetRetryItemForUser_Call struct {
	*mock.Call
}

// GetRetryItemForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - retryItemID string
func (_e *Repository_Expecter) GetRetryItemForUser(ctx interface{}, userID interface{}, retryItemID interface{}) *Repository_GetRetryItemForUser_Call {
	return &Repository_GetRetryItemForUser_Call{Call: _e.mock.On("GetRetryItemForUser", ctx, userID, retryItemID)}
}

func (_c *Repository_GetRetryItemForUser_Call) Run(run func(ctx context.Context, userID string, retryItemID string)) *Repository_GetRetryItemForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_GetRetryItemForUser_Call) Return(_a0 *model.RetryItem, _a1 error) *Repository_GetRetryItemForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetRetryItemForUser_Call) RunAndReturn(run func(context.Context, string, string) (*model.RetryItem, error)) *Repository_GetRetryItemForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetRetryItemsByIDs provides a mock function with given fields: ctx, userID, ids
func (_m *Repository) GetRetryItemsByIDs(ctx context.Context, userID string, ids []string) ([]model.RetryItem, error) {
	ret := _m.Called(ctx, userID, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetRetryItemsByIDs")
	}

	var r0 []model.RetryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) ([]model.RetryItem, error)); ok {
		return rf(ctx, userID, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) []model.RetryItem); ok {
		r0 = rf(ctx, userID, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RetryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, userID, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetRetryItemsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRetryItemsByIDs'
type Repository_GetRetryItemsByIDs_Call struct {
	*mock.Call
}

// GetRetryItemsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - ids []string
func (_e *Repository_Expecter) GetRetryItemsByIDs(ctx interface{}, userID interface{}, ids interface{}) *Repository_GetRetryItemsByIDs_Call {
	return &Repository_GetRetryItemsByIDs_Call{Call: _e.mock.On("GetRetryItemsByIDs", ctx, userID, ids)}
}

func (_c *Repository_GetRetryItemsByIDs_Call) Run(run func(ctx context.Context, userID string, ids []string)) *Repository_GetRetryItemsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *Repository_GetRetryItemsByIDs_Call) Return(_a0 []model.RetryItem, _a1 error) *Repository_GetRetryItemsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetRetryItemsByIDs_Call) RunAndReturn(run func(context.Context, string, []string) ([]model.RetryItem, error)) *Repository_GetRetryItemsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetSessionByID(ctx context.Context, id string) (*model.Session, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByID")
	}

	var r0 *model.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Session, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Session); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetSessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionByID'
type Repository_GetSessionByID_Call struct {
	*mock.Call
}

// GetSessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Repository_Expecter) GetSessionByID(ctx interface{}, id interface{}) *Repository_GetSessionByID_Call {
	return &Repository_GetSessionByID_Call{Call: _e.mock.On("GetSessionByID", ctx, id)}
}

func (_c *Repository_GetSessionByID_Call) Run(run func(ctx context.Context, id string)) *Repository_GetSessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_GetSessionByID_Call) Return(_a0 *model.Session, _a1 error) *Repository_GetSessionByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetSessionByID_Call) RunAndReturn(run func(context.Context, string) (*model.Session, error)) *Repository_GetSessionByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionForUser provides a mock function with given fields: ctx, userID, sessionID
func (_m *Repository) GetSessionForUser(ctx context.Context, userID string, sessionID string) (*model.Session, error) {
	ret := _m.Called(ctx, userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionForUser")
	}

	var r0 *model.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Session, error)); ok {
		return rf(ctx, userID, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Session); ok {
		r0 = rf(ctx, userID, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetSessionForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionForUser'
type Repository_GetSessionForUser_Call struct {
	*mock.Call
}

// GetSessionForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - sessionID string
func (_e *Repository_Expecter) GetSessionForUser(ctx interface{}, userID interface{}, sessionID interface{}) *Repository_GetSessionForUser_Call {
	return &Repository_GetSessionForUser_Call{Call: _e.mock.On("GetSessionForUser", ctx, userID, sessionID)}
}

func (_c *Repository_GetSessionForUser_Call) Run(run func(ctx context.Context, userID string, sessionID string)) *Repository_GetSessionForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_GetSessionForUser_Call) Return(_a0 *model.Session, _a1 error) *Repository_GetSessionForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetSessionForUser_Call) RunAndReturn(run func(context.Context, string, string) (*model.Session, error)) *Repository_GetSessionForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionTaskByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetSessionTaskByID(ctx context.Context, id string) (*model.SessionTask, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionTaskByID")
	}

	var r0 *model.SessionTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.SessionTask, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.SessionTask); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SessionTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetSessionTaskByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionTaskByID'
type Repository_GetSessionTaskByID_Call struct {
	*mock.Call
}

// GetSessionTaskByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Repository_Expecter) GetSessionTaskByID(ctx interface{}, id interface{}) *Repository_GetSessionTaskByID_Call {
	return &Repository_GetSessionTaskByID_Call{Call: _e.mock.On("GetSessionTaskByID", ctx, id)}
}

func (_c *Repository_GetSessionTaskByID_Call) Run(run func(ctx context.Context, id string)) *Repository_GetSessionTaskByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_GetSessionTaskByID_Call) Return(_a0 *model.SessionTask, _a1 error) *Repository_GetSessionTaskByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetSessionTaskByID_Call) RunAndReturn(run func(context.Context, string) (*model.SessionTask, error)) *Repository_GetSessionTaskByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionTaskForUser provides a mock function with given fields: ctx, userID, sessionTaskID
func (_m *Repository) GetSessionTaskForUser(ctx context.Context, userID string, sessionTaskID string) (*model.SessionTask, error) {
	ret := _m.Called(ctx, userID, sessionTaskID)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionTaskForUser")
	}

	var r0 *model.SessionTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.SessionTask, error)); ok {
		return rf(ctx, userID, sessionTaskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.SessionTask); ok {
		r0 = rf(ctx, userID, sessionTaskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SessionTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, sessionTaskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetSessionTaskForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionTaskForUser'
type Repository_GetSessionTaskForUser_Call struct {
	*mock.Call
}

// GetSessionTaskForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - sessionTaskID string
func (_e *Repository_Expecter) GetSessionTaskForUser(ctx interface{}, userID interface{}, sessionTaskID interface{}) *Repository_GetSessionTaskForUser_Call {
	return &Repository_GetSessionTaskForUser_Call{Call: _e.mock.On("GetSessionTaskForUser", ctx, userID, sessionTaskID)}
}

func (_c *Repository_GetSessionTaskForUser_Call) Run(run func(ctx context.Context, userID string, sessionTaskID string)) *Repository_GetSessionTaskForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_GetSessionTaskForUser_Call) Return(_a0 *model.SessionTask, _a1 error) *Repository_GetSessionTaskForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetSessionTaskForUser_Call) RunAndReturn(run func(context.Context, string, string) (*model.SessionTask, error)) *Repository_GetSessionTaskForUser_Call {
	_c.Call.Return(run)
	return _c
}

// InsertOutbox provides a mock function with given fields: ctx, eventName, payload
func (_m *Repository) InsertOutbox(ctx context.Context, eventName string, payload map[string]interface{}) error {
	ret := _m.Called(ctx, eventName, payload)

	if len(ret) == 0 {
		panic("no return value specified for InsertOutbox")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, eventName, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_InsertOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertOutbox'
type Repository_InsertOutbox_Call struct {
	*mock.Call
}

// InsertOutbox is a helper method to define mock.On call
//   - ctx context.Context
//   - eventName string
//   - payload map[string]interface{}
func (_e *Repository_Expecter) InsertOutbox(ctx interface{}, eventName interface{}, payload interface{}) *Repository_InsertOutbox_Call {
	return &Repository_InsertOutbox_Call{Call: _e.mock.On("InsertOutbox", ctx, eventName, payload)}
}

func (_c *Repository_InsertOutbox_Call) Run(run func(ctx context.Context, eventName string, payload map[string]interface{})) *Repository_InsertOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *Repository_InsertOutbox_Call) Return(_a0 error) *Repository_InsertOutbox_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_InsertOutbox_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}) error) *Repository_InsertOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// ListEvaluationsBySession provides a mock function with given fields: ctx, sessionID
func (_m *Repository) ListEvaluationsBySession(ctx context.Context, sessionID string) ([]model.EvaluationWithAttempt, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for ListEvaluationsBySession")
	}

	var r0 []model.EvaluationWithAttempt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.EvaluationWithAttempt, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.EvaluationWithAttempt); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.EvaluationWithAttempt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListEvaluationsBySession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEvaluationsBySession'
type Repository_ListEvaluationsBySession_Call struct {
	*mock.Call
}

// ListEvaluationsBySession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *Repository_Expecter) ListEvaluationsBySession(ctx interface{}, sessionID interface{}) *Repository_ListEvaluationsBySession_Call {
	return &Repository_ListEvaluationsBySession_Call{Call: _e.mock.On("ListEvaluationsBySession", ctx, sessionID)}
}

func (_c *Repository_ListEvaluationsBySession_Call) Run(run func(ctx context.Context, sessionID string)) *Repository_ListEvaluationsBySession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_ListEvaluationsBySession_Call) Return(_a0 []model.EvaluationWithAttempt, _a1 error) *Repository_ListEvaluationsBySession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListEvaluationsBySession_Call) RunAndReturn(run func(context.Context, string) ([]model.EvaluationWithAttempt, error)) *Repository_ListEvaluationsBySession_Call {
	_c.Call.Return(run)
	return _c
}

// ListPendingRetryItems provides a mock function with given fields: ctx, userID
func (_m *Repository) ListPendingRetryItems(ctx context.Context, userID string) ([]model.RetryItem, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingRetryItems")
	}

	var r0 []model.RetryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.RetryItem, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.RetryItem); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RetryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListPendingRetryItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPendingRetryItems'
type Repository_ListPendingRetryItems_Call struct {
	*mock.Call
}

// ListPendingRetryItems is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Repository_Expecter) ListPendingRetryItems(ctx interface{}, userID interface{}) *Repository_ListPendingRetryItems_Call {
	return &Repository_ListPendingRetryItems_Call{Call: _e.mock.On("ListPendingRetryItems", ctx, userID)}
}

func (_c *Repository_ListPendingRetryItems_Call) Run(run func(ctx context.Context, userID string)) *Repository_ListPendingRetryItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_ListPendingRetryItems_Call) Return(_a0 []model.RetryItem, _a1 error) *Repository_ListPendingRetryItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListPendingRetryItems_Call) RunAndReturn(run func(context.Context, string) ([]model.RetryItem, error)) *Repository_ListPendingRetryItems_Call {
	_c.Call.Return(run)
	return _c
}

// ListRetryItems provides a mock function with given fields: ctx, userID, status
func (_m *Repository) ListRetryItems(ctx context.Context, userID string, status *model.RetryItemStatus) ([]model.RetryItem, error) {
	ret := _m.Called(ctx, userID, status)

	if len(ret) == 0 {
		panic("no return value specified for ListRetryItems")
	}

	var r0 []model.RetryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.RetryItemStatus) ([]model.RetryItem, error)); ok {
		return rf(ctx, userID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.RetryItemStatus) []model.RetryItem); ok {
		r0 = rf(ctx, userID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RetryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *model.RetryItemStatus) error); ok {
		r1 = rf(ctx, userID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListRetryItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRetryItems'
type Repository_ListRetryItems_Call struct {
	*mock.Call
}

// ListRetryItems is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - status *model.RetryItemStatus
func (_e *Repository_Expecter) ListRetryItems(ctx interface{}, userID interface{}, status interface{}) *Repository_ListRetryItems_Call {
	return &Repository_ListRetryItems_Call{Call: _e.mock.On("ListRetryItems", ctx, userID, status)}
}

func (_c *Repository_ListRetryItems_Call) Run(run func(ctx context.Context, userID string, status *model.RetryItemStatus)) *Repository_ListRetryItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*model.RetryItemStatus))
	})
	return _c
}

func (_c *Repository_ListRetryItems_Call) Return(_a0 []model.RetryItem, _a1 error) *Repository_ListRetryItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListRetryItems_Call) RunAndReturn(run func(context.Context, string, *model.RetryItemStatus) ([]model.RetryItem, error)) *Repository_ListRetryItems_Call {
	_c.Call.Return(run)
	return _c
}

// ListRetryItemsBySession provides a mock function with given fields: ctx, sessionID
func (_m *Repository) ListRetryItemsBySession(ctx context.Context, sessionID string) ([]model.RetryItem, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for ListRetryItemsBySession")
	}

	var r0 []model.RetryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.RetryItem, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.RetryItem); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RetryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListRetryItemsBySession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRetryItemsBySession'
type Repository_ListRetryItemsBySession_Call struct {
	*mock.Call
}

// ListRetryItemsBySession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *Repository_Expecter) ListRetryItemsBySession(ctx interface{}, sessionID interface{}) *Repository_ListRetryItemsBySession_Call {
	return &Repository_ListRetryItemsBySession_Call{Call: _e.mock.On("ListRetryItemsBySession", ctx, sessionID)}
}

func (_c *Repository_ListRetryItemsBySession_Call) Run(run func(ctx context.Context, sessionID string)) *Repository_ListRetryItemsBySession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_ListRetryItemsBySession_Call) Return(_a0 []model.RetryItem, _a1 error) *Repository_ListRetryItemsBySession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListRetryItemsBySession_Call) RunAndReturn(run func(context.Context, string) ([]model.RetryItem, error)) *Repository_ListRetryItemsBySession_Call {
	_c.Call.Return(run)
	return _c
}

// ListSectionsBySession provides a mock function with given fields: ctx, sessionID
func (_m *Repository) ListSectionsBySession(ctx context.Context, sessionID string) ([]model.SessionSection, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for ListSectionsBySession")
	}

	var r0 []model.SessionSection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.SessionSection, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.SessionSection); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SessionSection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListSectionsBySession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSectionsBySession'
type Repository_ListSectionsBySession_Call struct {
	*mock.Call
}

// ListSectionsBySession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *Repository_Expecter) ListSectionsBySession(ctx interface{}, sessionID interface{}) *Repository_ListSectionsBySession_Call {
	return &Repository_ListSectionsBySession_Call{Call: _e.mock.On("ListSectionsBySession", ctx, sessionID)}
}

func (_c *Repository_ListSectionsBySession_Call) Run(run func(ctx context.Context, sessionID string)) *Repository_ListSectionsBySession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_ListSectionsBySession_Call) Return(_a0 []model.SessionSection, _a1 error) *Repository_ListSectionsBySession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListSectionsBySession_Call) RunAndReturn(run func(context.Context, string) ([]model.SessionSection, error)) *Repository_ListSectionsBySession_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasksBySession provides a mock function with given fields: ctx, sessionID
func (_m *Repository) ListTasksBySession(ctx context.Context, sessionID string) ([]model.SessionTask, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for ListTasksBySession")
	}

	var r0 []model.SessionTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.SessionTask, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.SessionTask); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SessionTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListTasksBySession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasksBySession'
type Repository_ListTasksBySession_Call struct {
	*mock.Call
}

// ListTasksBySession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *Repository_Expecter) ListTasksBySession(ctx interface{}, sessionID interface{}) *Repository_ListTasksBySession_Call {
	return &Repository_ListTasksBySession_Call{Call: _e.mock.On("ListTasksBySession", ctx, sessionID)}
}

func (_c *Repository_ListTasksBySession_Call) Run(run func(ctx context.Context, sessionID string)) *Repository_ListTasksBySession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_ListTasksBySession_Call) Return(_a0 []model.SessionTask, _a1 error) *Repository_ListTasksBySession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListTasksBySession_Call) RunAndReturn(run func(context.Context, string) ([]model.SessionTask, error)) *Repository_ListTasksBySession_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAttempt provides a mock function with given fields: ctx, attempt
func (_m *Repository) UpdateAttempt(ctx context.Context, attempt *model.Attempt) error {
	ret := _m.Called(ctx, attempt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAttempt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Attempt) error); ok {
		r0 = rf(ctx, attempt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAttempt'
type Repository_UpdateAttempt_Call struct {
	*mock.Call
}

// UpdateAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - attempt *model.Attempt
func (_e *Repository_Expecter) UpdateAttempt(ctx interface{}, attempt interface{}) *Repository_UpdateAttempt_Call {
	return &Repository_UpdateAttempt_Call{Call: _e.mock.On("UpdateAttempt", ctx, attempt)}
}

func (_c *Repository_UpdateAttempt_Call) Run(run func(ctx context.Context, attempt *model.Attempt)) *Repository_UpdateAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Attempt))
	})
	return _c
}

func (_c *Repository_UpdateAttempt_Call) Return(_a0 error) *Repository_UpdateAttempt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateAttempt_Call) RunAndReturn(run func(context.Context, *model.Attempt) error) *Repository_UpdateAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRetryItem provides a mock function with given fields: ctx, item
func (_m *Repository) UpdateRetryItem(ctx context.Context, item *model.RetryItem) error {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRetryItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.RetryItem) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateRetryItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRetryItem'
type Repository_UpdateRetryItem_Call struct {
	*mock.Call
}

// UpdateRetryItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item *model.RetryItem
func (_e *Repository_Expecter) UpdateRetryItem(ctx interface{}, item interface{}) *Repository_UpdateRetryItem_Call {
	return &Repository_UpdateRetryItem_Call{Call: _e.mock.On("UpdateRetryItem", ctx, item)}
}

func (_c *Repository_UpdateRetryItem_Call) Run(run func(ctx context.Context, item *model.RetryItem)) *Repository_UpdateRetryItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.RetryItem))
	})
	return _c
}

func (_c *Repository_UpdateRetryItem_Call) Return(_a0 error) *Repository_UpdateRetryItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateRetryItem_Call) RunAndReturn(run func(context.Context, *model.RetryItem) error) *Repository_UpdateRetryItem_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSection provides a mock function with given fields: ctx, section
func (_m *Repository) UpdateSection(ctx context.Context, section *model.SessionSection) error {
	ret := _m.Called(ctx, section)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SessionSection) error); ok {
		r0 = rf(ctx, section)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateSection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSection'
type Repository_UpdateSection_Call struct {
	*mock.Call
}

// UpdateSection is a helper method to define mock.On call
//   - ctx context.Context
//   - section *model.SessionSection
func (_e *Repository_Expecter) UpdateSection(ctx interface{}, section interface{}) *Repository_UpdateSection_Call {
	return &Repository_UpdateSection_Call{Call: _e.mock.On("UpdateSection", ctx, section)}
}

func (_c *Repository_UpdateSection_Call) Run(run func(ctx context.Context, section *model.SessionSection)) *Repository_UpdateSection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SessionSection))
	})
	return _c
}

func (_c *Repository_UpdateSection_Call) Return(_a0 error) *Repository_UpdateSection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateSection_Call) RunAndReturn(run func(context.Context, *model.SessionSection) error) *Repository_UpdateSection_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSession provides a mock function with given fields: ctx, session
func (_m *Repository) UpdateSession(ctx context.Context, session *model.Session) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSession'
type Repository_UpdateSession_Call struct {
	*mock.Call
}

// UpdateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session *model.Session
func (_e *Repository_Expecter) UpdateSession(ctx interface{}, session interface{}) *Repository_UpdateSession_Call {
	return &Repository_UpdateSession_Call{Call: _e.mock.On("UpdateSession", ctx, session)}
}

func (_c *Repository_UpdateSession_Call) Run(run func(ctx context.Context, session *model.Session)) *Repository_UpdateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Session))
	})
	return _c
}

func (_c *Repository_UpdateSession_Call) Return(_a0 error) *Repository_UpdateSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateSession_Call) RunAndReturn(run func(context.Context, *model.Session) error) *Repository_UpdateSession_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSessionTask provides a mock function with given fields: ctx, task
func (_m *Repository) UpdateSessionTask(ctx context.Context, task *model.SessionTask) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSessionTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SessionTask) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateSessionTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSessionTask'
type Repository_UpdateSessionTask_Call struct {
	*mock.Call
}

// UpdateSessionTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task *model.SessionTask
func (_e *Repository_Expecter) UpdateSessionTask(ctx interface{}, task interface{}) *Repository_UpdateSessionTask_Call {
	return &Repository_UpdateSessionTask_Call{Call: _e.mock.On("UpdateSessionTask", ctx, task)}
}

func (_c *Repository_UpdateSessionTask_Call) Run(run func(ctx context.Context, task *model.SessionTask)) *Repository_UpdateSessionTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SessionTask))
	})
	return _c
}

func (_c *Repository_UpdateSessionTask_Call) Return(_a0 error) *Repository_UpdateSessionTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateSessionTask_Call) RunAndReturn(run func(context.Context, *model.SessionTask) error) *Repository_UpdateSessionTask_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function with given fields: ctx, fn
func (_m *Repository) WithTx(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type Repository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *Repository_Expecter) WithTx(ctx interface{}, fn interface{}) *Repository_WithTx_Call {
	return &Repository_WithTx_Call{Call: _e.mock.On("WithTx", ctx, fn)}
}

func (_c *Repository_WithTx_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *Repository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *Repository_WithTx_Call) Return(_a0 error) *Repository_WithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_WithTx_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *Repository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
