// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	interview "github.com/sedorofeevd/project-druzya/services/ai/internal/adapter/interview"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// AckOutboxEvents provides a mock function with given fields: ctx, ids
func (_m *Client) AckOutboxEvents(ctx context.Context, ids []string) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for AckOutboxEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_AckOutboxEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AckOutboxEvents'
type Client_AckOutboxEvents_Call struct {
	*mock.Call
}

// AckOutboxEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *Client_Expecter) AckOutboxEvents(ctx interface{}, ids interface{}) *Client_AckOutboxEvents_Call {
	return &Client_AckOutboxEvents_Call{Call: _e.mock.On("AckOutboxEvents", ctx, ids)}
}

func (_c *Client_AckOutboxEvents_Call) Run(run func(ctx context.Context, ids []string)) *Client_AckOutboxEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *Client_AckOutboxEvents_Call) Return(_a0 error) *Client_AckOutboxEvents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_AckOutboxEvents_Call) RunAndReturn(run func(context.Context, []string) error) *Client_AckOutboxEvents_Call {
	_c.Call.Return(run)
	return _c
}

// ClaimOutboxEvents provides a mock function with given fields: ctx, eventName, limit
func (_m *Client) ClaimOutboxEvents(ctx context.Context, eventName string, limit int) ([]interview.OutboxEvent, error) {
	ret := _m.Called(ctx, eventName, limit)

	if len(ret) == 0 {
		panic("no return value specified for ClaimOutboxEvents")
	}

	var r0 []interview.OutboxEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]interview.OutboxEvent, error)); ok {
		return rf(ctx, eventName, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []interview.OutboxEvent); ok {
		r0 = rf(ctx, eventName, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interview.OutboxEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, eventName, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ClaimOutboxEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimOutboxEvents'
type Client_ClaimOutboxEvents_Call struct {
	*mock.Call
}

// ClaimOutboxEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - eventName string
//   - limit int
func (_e *Client_Expecter) ClaimOutboxEvents(ctx interface{}, eventName interface{}, limit interface{}) *Client_ClaimOutboxEvents_Call {
	return &Client_ClaimOutboxEvents_Call{Call: _e.mock.On("ClaimOutboxEvents", ctx, eventName, limit)}
}

func (_c *Client_ClaimOutboxEvents_Call) Run(run func(ctx context.Context, eventName string, limit int)) *Client_ClaimOutboxEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *Client_ClaimOutboxEvents_Call) Return(_a0 []interview.OutboxEvent, _a1 error) *Client_ClaimOutboxEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_ClaimOutboxEvents_Call) RunAndReturn(run func(context.Context, string, int) ([]interview.OutboxEvent, error)) *Client_ClaimOutboxEvents_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteEvaluation provides a mock function with given fields: ctx, input
func (_m *Client) CompleteEvaluation(ctx context.Context, input interview.CompleteEvaluationInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CompleteEvaluation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interview.CompleteEvaluationInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_CompleteEvaluation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteEvaluation'
type Client_CompleteEvaluation_Call struct {
	*mock.Call
}

// CompleteEvaluation is a helper method to define mock.On call
//   - ctx context.Context
//   - input interview.CompleteEvaluationInput
func (_e *Client_Expecter) CompleteEvaluation(ctx interface{}, input interface{}) *Client_CompleteEvaluation_Call {
	return &Client_CompleteEvaluation_Call{Call: _e.mock.On("CompleteEvaluation", ctx, input)}
}

func (_c *Client_CompleteEvaluation_Call) Run(run func(ctx context.Context, input interview.CompleteEvaluationInput)) *Client_CompleteEvaluation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interview.CompleteEvaluationInput))
	})
	return _c
}

func (_c *Client_CompleteEvaluation_Call) Return(_a0 error) *Client_CompleteEvaluation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_CompleteEvaluation_Call) RunAndReturn(run func(context.Context, interview.CompleteEvaluationInput) error) *Client_CompleteEvaluation_Call {
	_c.Call.Return(run)
	return _c
}

// FailEvaluation provides a mock function with given fields: ctx, attemptID, reason
func (_m *Client) FailEvaluation(ctx context.Context, attemptID string, reason *string) error {
	ret := _m.Called(ctx, attemptID, reason)

	if len(ret) == 0 {
		panic("no return value specified for FailEvaluation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string) error); ok {
		r0 = rf(ctx, attemptID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_FailEvaluation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailEvaluation'
type Client_FailEvaluation_Call struct {
	*mock.Call
}

// FailEvaluation is a helper method to define mock.On call
//   - ctx context.Context
//   - attemptID string
//   - reason *string
func (_e *Client_Expecter) FailEvaluation(ctx interface{}, attemptID interface{}, reason interface{}) *Client_FailEvaluation_Call {
	return &Client_FailEvaluation_Call{Call: _e.mock.On("FailEvaluation", ctx, attemptID, reason)}
}

func (_c *Client_FailEvaluation_Call) Run(run func(ctx context.Context, attemptID string, reason *string)) *Client_FailEvaluation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string))
	})
	return _c
}

func (_c *Client_FailEvaluation_Call) Return(_a0 error) *Client_FailEvaluation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_FailEvaluation_Call) RunAndReturn(run func(context.Context, string, *string) error) *Client_FailEvaluation_Call {
	_c.Call.Return(run)
	return _c
}

// FailOutboxEvent provides a mock function with given fields: ctx, id, errMsg
func (_m *Client) FailOutboxEvent(ctx context.Context, id string, errMsg string) error {
	ret := _m.Called(ctx, id, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for FailOutboxEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, errMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_FailOutboxEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailOutboxEvent'
type Client_FailOutboxEvent_Call struct {
	*mock.Call
}

// FailOutboxEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - errMsg string
func (_e *Client_Expecter) FailOutboxEvent(ctx interface{}, id interface{}, errMsg interface{}) *Client_FailOutboxEvent_Call {
	return &Client_FailOutboxEvent_Call{Call: _e.mock.On("FailOutboxEvent", ctx, id, errMsg)}
}

func (_c *Client_FailOutboxEvent_Call) Run(run func(ctx context.Context, id string, errMsg string)) *Client_FailOutboxEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Client_FailOutboxEvent_Call) Return(_a0 error) *Client_FailOutboxEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_FailOutboxEvent_Call) RunAndReturn(run func(context.Context, string, string) error) *Client_FailOutboxEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttempt provides a mock function with given fields: ctx, attemptID
func (_m *Client) GetAttempt(ctx context.Context, attemptID string) (*interview.Attempt, error) {
	ret := _m.Called(ctx, attemptID)

	if len(ret) == 0 {
		panic("no return value specified for GetAttempt")
	}

	var r0 *interview.Attempt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*interview.Attempt, error)); ok {
		return rf(ctx, attemptID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *interview.Attempt); ok {
		r0 = rf(ctx, attemptID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interview.Attempt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, attemptID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttempt'
type Client_GetAttempt_Call struct {
	*mock.Call
}

// GetAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - attemptID string
func (_e *Client_Expecter) GetAttempt(ctx interface{}, attemptID interface{}) *Client_GetAttempt_Call {
	return &Client_GetAttempt_Call{Call: _e.mock.On("GetAttempt", ctx, attemptID)}
}

func (_c *Client_GetAttempt_Call) Run(run func(ctx context.Context, attemptID string)) *Client_GetAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_GetAttempt_Call) Return(_a0 *interview.Attempt, _a1 error) *Client_GetAttempt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetAttempt_Call) RunAndReturn(run func(context.Context, string) (*interview.Attempt, error)) *Client_GetAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
