// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	content "github.com/sedorofeevd/project-druzya/services/interview/internal/adapter/content"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// GetInterviewTemplateDetail provides a mock function with given fields: ctx, templateID
func (_m *Client) GetInterviewTemplateDetail(ctx context.Context, templateID string) (*content.TemplateDetail, error) {
	ret := _m.Called(ctx, templateID)

	if len(ret) == 0 {
		panic("no return value specified for GetInterviewTemplateDetail")
	}

	var r0 *content.TemplateDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*content.TemplateDetail, error)); ok {
		return rf(ctx, templateID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *content.TemplateDetail); ok {
		r0 = rf(ctx, templateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.TemplateDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, templateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetInterviewTemplateDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInterviewTemplateDetail'
type Client_GetInterviewTemplateDetail_Call struct {
	*mock.Call
}

// GetInterviewTemplateDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - templateID string
func (_e *Client_Expecter) GetInterviewTemplateDetail(ctx interface{}, templateID interface{}) *Client_GetInterviewTemplateDetail_Call {
	return &Client_GetInterviewTemplateDetail_Call{Call: _e.mock.On("GetInterviewTemplateDetail", ctx, templateID)}
}

func (_c *Client_GetInterviewTemplateDetail_Call) Run(run func(ctx context.Context, templateID string)) *Client_GetInterviewTemplateDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_GetInterviewTemplateDetail_Call) Return(_a0 *content.TemplateDetail, _a1 error) *Client_GetInterviewTemplateDetail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetInterviewTemplateDetail_Call) RunAndReturn(run func(context.Context, string) (*content.TemplateDetail, error)) *Client_GetInterviewTemplateDetail_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function with given fields: ctx, taskID
func (_m *Client) GetTask(ctx context.Context, taskID string) (*content.Task, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 *content.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*content.Task, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *content.Task); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type Client_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *Client_Expecter) GetTask(ctx interface{}, taskID interface{}) *Client_GetTask_Call {
	return &Client_GetTask_Call{Call: _e.mock.On("GetTask", ctx, taskID)}
}

func (_c *Client_GetTask_Call) Run(run func(ctx context.Context, taskID string)) *Client_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_GetTask_Call) Return(_a0 *content.Task, _a1 error) *Client_GetTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetTask_Call) RunAndReturn(run func(context.Context, string) (*content.Task, error)) *Client_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// ListInterviewTemplates provides a mock function with given fields: ctx, companyID, activeOnly, limit
func (_m *Client) ListInterviewTemplates(ctx context.Context, companyID string, activeOnly bool, limit int) ([]content.InterviewTemplate, error) {
	ret := _m.Called(ctx, companyID, activeOnly, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListInterviewTemplates")
	}

	var r0 []content.InterviewTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool, int) ([]content.InterviewTemplate, error)); ok {
		return rf(ctx, companyID, activeOnly, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool, int) []content.InterviewTemplate); ok {
		r0 = rf(ctx, companyID, activeOnly, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]content.InterviewTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool, int) error); ok {
		r1 = rf(ctx, companyID, activeOnly, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ListInterviewTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInterviewTemplates'
type Client_ListInterviewTemplates_Call struct {
	*mock.Call
}

// ListInterviewTemplates is a helper method to define mock.On call
//   - ctx context.Context
//   - companyID string
//   - activeOnly bool
//   - limit int
func (_e *Client_Expecter) ListInterviewTemplates(ctx interface{}, companyID interface{}, activeOnly interface{}, limit interface{}) *Client_ListInterviewTemplates_Call {
	return &Client_ListInterviewTemplates_Call{Call: _e.mock.On("ListInterviewTemplates", ctx, companyID, activeOnly, limit)}
}

func (_c *Client_ListInterviewTemplates_Call) Run(run func(ctx context.Context, companyID string, activeOnly bool, limit int)) *Client_ListInterviewTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool), args[3].(int))
	})
	return _c
}

func (_c *Client_ListInterviewTemplates_Call) Return(_a0 []content.InterviewTemplate, _a1 error) *Client_ListInterviewTemplates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_ListInterviewTemplates_Call) RunAndReturn(run func(context.Context, string, bool, int) ([]content.InterviewTemplate, error)) *Client_ListInterviewTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function with given fields: ctx, taskType, limit
func (_m *Client) ListTasks(ctx context.Context, taskType string, limit int) ([]content.Task, error) {
	ret := _m.Called(ctx, taskType, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 []content.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]content.Task, error)); ok {
		return rf(ctx, taskType, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []content.Task); ok {
		r0 = rf(ctx, taskType, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]content.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, taskType, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type Client_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - taskType string
//   - limit int
func (_e *Client_Expecter) ListTasks(ctx interface{}, taskType interface{}, limit interface{}) *Client_ListTasks_Call {
	return &Client_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx, taskType, limit)}
}

func (_c *Client_ListTasks_Call) Run(run func(ctx context.Context, taskType string, limit int)) *Client_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *Client_ListTasks_Call) Return(_a0 []content.Task, _a1 error) *Client_ListTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_ListTasks_Call) RunAndReturn(run func(context.Context, string, int) ([]content.Task, error)) *Client_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
