/**
 * @generated by design/tokens/emit.mjs — DO NOT EDIT.
 * Edit design/tokens/source.mjs, then run `make tokens`.
 */

export const motion = {
  dur: {
    micro: 80,
    small: 160,
    medium: 240,
    large: 360,
    xlarge: 520,
    xxlarge: 720,
    cinematic: 1100,
  },
  ease: {
    standard: 'cubic-bezier(0.2, 0.7, 0.2, 1)',
    emphasized: 'cubic-bezier(0.16, 1, 0.3, 1)',
    decelerate: 'cubic-bezier(0, 0, 0.2, 1)',
    accelerate: 'cubic-bezier(0.4, 0, 1, 1)',
  },
} as const;


