// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	content "github.com/sedorofeevd/project-druzya/services/ai/internal/adapter/content"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// GetTaskBundle provides a mock function with given fields: ctx, taskID
func (_m *Client) GetTaskBundle(ctx context.Context, taskID string) (*content.TaskBundle, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskBundle")
	}

	var r0 *content.TaskBundle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*content.TaskBundle, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *content.TaskBundle); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.TaskBundle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetTaskBundle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskBundle'
type Client_GetTaskBundle_Call struct {
	*mock.Call
}

// GetTaskBundle is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *Client_Expecter) GetTaskBundle(ctx interface{}, taskID interface{}) *Client_GetTaskBundle_Call {
	return &Client_GetTaskBundle_Call{Call: _e.mock.On("GetTaskBundle", ctx, taskID)}
}

func (_c *Client_GetTaskBundle_Call) Run(run func(ctx context.Context, taskID string)) *Client_GetTaskBundle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_GetTaskBundle_Call) Return(_a0 *content.TaskBundle, _a1 error) *Client_GetTaskBundle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetTaskBundle_Call) RunAndReturn(run func(context.Context, string) (*content.TaskBundle, error)) *Client_GetTaskBundle_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
